Project GAIM: auxiliary_funs.cpp File Reference
auxiliary_funs.cpp File Reference
Functions
REAL_ vector_norm (std::vector< REAL_ > x)
Vector's Euclidean norm.
std::vector< REAL_ > compute_population_norms (std::vector< GA > x)
Compute population norms.
int argmax (std::vector< REAL_ > x)
Argmax.
int argmin (std::vector< REAL_ > x)
Argmin.
ga_results_s return_best_results (std::vector< GA > population, std::string return_type)
Return best results.
size_t int_random (size_t a, size_t b)
Integer uniform distribution.
REAL_ float_random (REAL_ a, REAL_ b)
Float uniform distribution.
void remove_at (std::vector< size_t > &v, std::vector< size_t >::size_type n)
Removes an element from a vector by swaping the element at position n with the last one and poping it out of the vector.
REAL_ cumulative_fitness (std::vector< individual_s > population)
Computes the cumulative fitness of a population based on which individuals have not been yet selected.
REAL_ maximum_fitness (std::vector< individual_s > population)
A naive implementation of maximum.
REAL_ nonselected_maximum_fitness (std::vector< individual_s > population)
Computes the maximum fitness of all the non-selected (from a selection operator) indivuduals of a population.
bool compare_fitness (const individual_s x, const individual_s y)
This helper function compares the fitness of two individuals and returns true if the first argument has a smaller fitness or false otherwise.
REAL_ average_fitness (REAL_ x, const individual_s y)
This is a helper function serving as an binary operator for std:accumulate.
bool is_path_exist (const std::string &str)
Checks if the given path (directory or file) exists.
int remove_file (const std::string fname)
Deletes a file.
int mkdir_ (const std::string &path)
Attempts to make a directory.
int make_dir (const std::string &path)
Attempts to make a directory.
Detailed Description
Auxiliary functions for the GAIM package, encompassing helpers for arithmetic with individual fitnesses and wrappers for directory I/O.
Definition in file auxiliary_funs.cpp.
Function Documentation
argmax()
int argmax (std::vector< REAL_ > x)
Argmax.
It returns the index of the maximum element in a vector.
Parameters
[in] x A vector of type REAL_
Returns
An integer as the index of the maximum element in vector x
Definition at line 74 of file auxiliary_funs.cpp.
References distance().
Referenced by return_best_results().
argmin()
int argmin (std::vector< REAL_ > x)
Argmin.
It returns the index of the minimum element in a vector.
Parameters
[in] x A vector of type REAL_
Returns
An integer as the index of the minimum element in vector x
Definition at line 88 of file auxiliary_funs.cpp.
References distance().
Referenced by return_best_results().
average_fitness()
REAL_ average_fitness (REAL_ x, const individual_s y)
This is a helper function serving as an binary operator for std:accumulate.
It helps add up the fitness belonging to individuals so that the cumulative fitness in the population can be computed, which is necessary for roulette-wheel selection, etc.
See also
one_generation_step()
Parameters
[in] x REAL_, it is the current accumulated fitness.
[in] y Data struct of individual_s type, it provides the new fitness of an idividual.
Returns
The current accumulated fitness yielded in the accumulation (usually for the whole population.)
Definition at line 272 of file auxiliary_funs.cpp.
References individual::fitness.
Referenced by GA::roulette_wheel_selection(), and GA::run_one_generation().
compare_fitness()
bool compare_fitness (const individual_s x, const individual_s y)
This helper function compares the fitness of two individuals and returns true if the first argument has a smaller fitness or false otherwise.
Auxiliary Functions declarations.
Parameters
[in] x Data struct of type const individual_s.
[in] y Data struct of type const individual_s.
Returns
True if x.fitness < y.fitness, false otherwise.
Definition at line 252 of file auxiliary_funs.cpp.
References individual::fitness.
Referenced by GA::linear_rank_selection(), GA::next_generation(), GA::sort_population(), and GA::truncation_selection().
compute_population_norms()
std::vector<REAL_> compute_population_norms (std::vector< GA > x)
Compute population norms.
It computes the Euclidean norms of all individual's genome within a population.
Parameters
[in] a A vector of type GA
Returns
A vector of REAL_ that contains the norms of all population's individuals
Definition at line 59 of file auxiliary_funs.cpp.
References vector_norm().
Referenced by return_best_results().
cumulative_fitness()
REAL_ cumulative_fitness (std::vector< individual_s > population)
Computes the cumulative fitness of a population based on which individuals have not been yet selected.
This function is used in the roulette_wheel_selection with replacement.
Parameters
[in] population A vector of the entire population.
Returns
The cumulative fitness of a population.
See also
roulette_wheel_selection()
Definition at line 184 of file auxiliary_funs.cpp.
Referenced by GA::roulette_wheel_selection().
float_random()
REAL_ float_random (REAL_ a, REAL_ b)
Float uniform distribution.
It returns a float random number in the interval [a, b] (uniform distribution).
Parameters
[in] a Lower limit of range [a, b] from which a random float will be drawn.
[in] b Upper limit of range [a, b].
Returns
A float number in [a, b].
Definition at line 151 of file auxiliary_funs.cpp.
Referenced by calculate_whitley_factor(), GA::roulette_wheel_selection(), and GA::stochastic_roulette_wheel_selection().
int_random()
size_t int_random (size_t a, size_t b)
Integer uniform distribution.
It returns an integer random number in the interval [a, b] (uniform distribution).
Parameters
[in] a Lower limit of range [a, b] from which a random integer will be drawn.
[in] b Upper limit of range [a, b].
Returns
An integer number in [a, b].
Definition at line 134 of file auxiliary_funs.cpp.
Referenced by GA::random_selection(), return_best_results(), GA::stochastic_roulette_wheel_selection(), and GA::truncation_selection().
is_path_exist()
bool is_path_exist (const std::string & str)
Checks if the given path (directory or file) exists.
Parameters
str const string that contains the name of the path.
Returns
True if the path exists and false otherwise.
Definition at line 284 of file auxiliary_funs.cpp.
Referenced by make_dir(), print_avg_fitness(), print_best_genome(), print_bsf(), and print_fitness().
make_dir()
int make_dir (const std::string & path)
Attempts to make a directory.
Parameters
[in] path const string that contains the name (path) of the new directory.
Returns
Zero upon successfully created directory, one otherwise.
Definition at line 332 of file auxiliary_funs.cpp.
References is_path_exist(), and mkdir_().
Referenced by ga_optimization(), ga_optimization_python(), independent_runs(), read_parameters_file(), and run_islands().
maximum_fitness()
REAL_ maximum_fitness (std::vector< individual_s > population)
A naive implementation of maximum.
This function finds the maximum fitness and returns it.
Parameters
[in] population A vector of the entire population.
Returns
The maximum fitness of a population.
Definition at line 203 of file auxiliary_funs.cpp.
Referenced by GA::stochastic_roulette_wheel_selection().
mkdir_()
int mkdir_ (const std::string & path)
Attempts to make a directory.
Parameters
[in] path const string that contains the name (path) of the new directory.
Returns
Zero upon successfully created directory, one otherwise.
Definition at line 312 of file auxiliary_funs.cpp.
Referenced by make_dir().
nonselected_maximum_fitness()
REAL_ nonselected_maximum_fitness (std::vector< individual_s > population)
Computes the maximum fitness of all the non-selected (from a selection operator) indivuduals of a population.
Note
This functions is meant to be used with selection methods that use the maximum fitness of a population and have the selection-with-replacement option disabled.
Parameters
[in] population A vector of the entire population.
Returns
The maximum fitness of a population (of the non-selected individuals).
Definition at line 229 of file auxiliary_funs.cpp.
Referenced by GA::stochastic_roulette_wheel_selection().
remove_at()
void remove_at (std::vector< size_t > & v, std::vector< size_t >::size_type n)
Removes an element from a vector by swaping the element at position n with the last one and poping it out of the vector.
Parameters
[in] v The input vector from whith an element will be deleted.
[in] n The size_type of the vector (position of deleted element).
Returns
(void)
Definition at line 167 of file auxiliary_funs.cpp.
Referenced by GA::ktournament_selection(), and GA::stochastic_roulette_wheel_selection().
remove_file()
int remove_file (const std::string fname)
Deletes a file.
Parameters
[in] fname const string that contains the name of the file to being deleted.
Returns
Zero in the case of successful deletion, non-zero value otherwise.
Definition at line 298 of file auxiliary_funs.cpp.
return_best_results()
ga_results_s return_best_results (std::vector< GA > population, std::string return_type)
Return best results.
It computes the best genome based on the Euclidean norm.
Parameters
[in] x A vector of type REAL_
Returns
A data structure of type ga_results_s
Definition at line 103 of file auxiliary_funs.cpp.
References argmax(), argmin(), ga_results::average_fitness, ga_results::bsf, compute_population_norms(), ga_results::genome, and int_random().
Referenced by independent_runs(), and run_islands().
vector_norm()
REAL_ vector_norm (std::vector< REAL_ > x)
Vector's Euclidean norm.
It computes the Euclidean norm of a vector of type REAL_.
Parameters
[in] x A vector of type REAL_
Returns
The norm of x as type REAL_
Definition at line 41 of file auxiliary_funs.cpp.
Referenced by compute_population_norms().