Project GAIM: GA Class Reference
GA Class Reference
Genetic Algorithm main class.
#include <gaim.h>
Public Member Functions
GA (ga_parameter_s *)
Constructor method of GA class.
~GA ()
Destructor method of GA.
std::vector< individual_s > ktournament_selection (std::vector< individual_s > &)
Genetic Algorithm basic operators.
std::vector< individual_s > truncation_selection (std::vector< individual_s > &)
Implements a truncation selection operator.
std::vector< individual_s > linear_rank_selection (std::vector< individual_s > &)
Implements a linear rank selection mechanism.
std::vector< individual_s > random_selection (std::vector< individual_s > &)
Implements a random selection.
std::vector< individual_s > roulette_wheel_selection (std::vector< individual_s > &)
Implements a roulette-wheel selection (or fitness-proportionate selection) mechanism.
std::vector< individual_s > stochastic_roulette_wheel_selection (std::vector< individual_s > &)
Parent selection method proposed by Lipowski A.
std::vector< individual_s > whitley_selection (std::vector< individual_s > &)
Parent selection method proposed by Darrell Whitley in his GENITOR paper: "The GENITOR Algorithm and Selection Pressure: Why Rank-Based Allocation of Reproductive Trials is Best", ", D.
void select_selection_method (void)
This method assigns the appropriate selection method to selection pointer function.
std::vector< REAL_ > one_point_crossover (std::vector< REAL_ >, std::vector< REAL_ >)
Crossover operator methods.
std::vector< REAL_ > two_point_crossover (std::vector< REAL_ >, std::vector< REAL_ >)
Two-point crossover operator.
std::vector< REAL_ > uniform_crossover (std::vector< REAL_ >, std::vector< REAL_ >)
Uniform crossover operator.
std::vector< REAL_ > flat_crossover (std::vector< REAL_ >, std::vector< REAL_ >)
Flat crossover operator.
std::vector< REAL_ > discrete_crossover (std::vector< REAL_ >, std::vector< REAL_ >)
Discrete crossover operator.
std::vector< REAL_ > order_one_crossover (std::vector< REAL_ >, std::vector< REAL_ >)
Order-one crossover operator.
void select_crossover_method (void)
This method assigns the appropriate crossover method to crossover pointer function.
std::vector< REAL_ > delta_mutation (std::vector< REAL_ >)
Mutation operator methods.
std::vector< REAL_ > random_mutation (std::vector< REAL_ >)
Random mutation operator.
std::vector< REAL_ > nonuniform_mutation (std::vector< REAL_ >)
Non-uniform mutation operator.
std::vector< REAL_ > fusion_mutation (std::vector< REAL_ >)
Fusion mutation operator method.
std::vector< REAL_ > swap_mutation (std::vector< REAL_ >)
Swap mutation operator method.
void select_mutation_method (void)
This method assigns the appropriate mutation operator based on the chosen mutation method.
void evaluation (std::vector< individual_s > &)
Genetic Algorithm secondary operations.
void next_generation (size_t)
Generate the next generation out of current individuals and.
void reset_selection_flags ()
Reset the flag is_selected (used from selections methods when.
void clip_genome ()
Clips the values of genes for each individual based on its lower.
void sort_population (void)
Sorting individuals based on their fitness value.
void run_one_generation (void)
Main routine for running one single generation step.
void evolve (size_t, size_t, pr_parameter_s *)
Main routine for evolving a population over generations.
std::vector< REAL_ > & get_bsf ()
std::vector< REAL_ > & get_best_genome ()
std::vector< REAL_ > & get_average_fitness ()
Public Attributes
std::vector< individual_s >(GA::* selection)(std::vector< individual_s > &)
Selection pointer function.
std::vector< REAL_ >(GA::* crossover)(std::vector< REAL_ >, std::vector< REAL_ >)
Crossover pointer function.
std::vector< REAL_ >(GA::* mutation)(std::vector< REAL_ >)
Mutation pointer function.
REAL_(* fitness)(REAL_ *, size_t)
std::vector< individual_s > population
std::vector< individual_s > offsprings
Individuals population vector.
std::vector< individual_s > sorted_population
Offsprings vector.
individual_s best_individual
Sorted population vector.
std::vector< REAL_ > bsf
Best individual (keep track)
std::vector< REAL_ > fit_avg
BSF vector (keep track)
std::vector< REAL_ > hfi
Average fitness vector (keep track)
std::vector< REAL_ > lfi
Highest fitness in the population.
std::vector< REAL_ > bsf_genome
Lowest fitness in the population.
Private Attributes
std::vector< REAL_ > alpha
BSF genome.
std::vector< REAL_ > beta
std::vector< individual_s > immigrant
Genome's interval limits [a, b].
std::string selection_method
Immigrants vector (buffer)
std::string crossover_method
std::string mutation_method
REAL_ bias
REAL_ mutation_rate
Bias term for Whitley selection metehod.
REAL_ variance
REAL_ low_bound
REAL_ up_bound
size_t mu
size_t lambda
Number of individuals within a population.
size_t replace_perc
Number of offsprings.
size_t genome_size
Number of individuals being replaced.
size_t num_parents
Genome size (number of genes)
size_t lower_bound
Number of parents per generation to select from.
size_t time
Starting index for truncation selection.
size_t generations
size_t order
int k
bool replace
k-tournament order
bool is_real
If replace is enabled, then selected parents are replaced.
Friends
class IM
Detailed Description
Genetic Algorithm main class.
GA is the main class for seting up and running an optimization process. It contains all the methods for performing operations such as selection, crossover, and mutation.
Definition at line 254 of file gaim.h.
Constructor & Destructor Documentation
GA()
GA::GA (ga_parameter_s * ga_pms)
Constructor method of GA class.
Constructor of GA class.
It initializes all the necessary parameters and vectors for evolving a population of individuals based on a predetermined Genetic Algorithm (GA).
Parameters
[in] ga_pms A structure that contains all the parameters for the GA
Returns
Nothing
Definition at line 39 of file genetic_alg.cpp.
References parameter_ga::a, alpha, parameter_ga::b, beta, parameter_sel::bias, bias, parameter_ga::clipping, parameter_ga::clipping_fname, parameter_ga::cross_pms, parameter_cross::crossover_method, crossover_method, fitness, parameter_ga::genome_size, genome_size, parameter_mut::is_real, is_real, parameter_sel::k, k, lambda, parameter_mut::low_bound, low_bound, parameter_sel::lower_bound, lower_bound, mu, parameter_ga::mut_pms, parameter_mut::mutation_method, mutation_method, parameter_mut::mutation_rate, mutation_rate, parameter_ga::num_offsprings, parameter_sel::num_parents, num_parents, parameter_ga::num_replacement, offsprings, parameter_mut::order, order, population, parameter_ga::population_size, parameter_sel::replace, replace, replace_perc, parameter_ga::sel_pms, select_crossover_method(), select_mutation_method(), select_selection_method(), parameter_sel::selection_method, selection_method, sorted_population, sphere(), parameter_mut::time, time, parameter_mut::up_bound, up_bound, parameter_mut::variance, and variance.
~GA()
GA::~GA ()
Destructor method of GA.
Destructor of GA class.
Definition at line 172 of file genetic_alg.cpp.
References offsprings, population, and sorted_population.
Member Function Documentation
clip_genome()
void GA::clip_genome ()
Clips the values of genes for each individual based on its lower.
Clips the value of genes indipendently based on predermined lower and upper boundaries.
Parameters
[in] (void)
Returns
Nothing (void)
Warning
This methods has to be called only when the lower and upper boundaries (limits) for every individual's genome have been initialized properly.
Definition at line 271 of file genetic_alg.cpp.
References population.
Referenced by run_one_generation().
delta_mutation()
std::vector< REAL_ > GA::delta_mutation (std::vector< REAL_ > genome)
Mutation operator methods.
This function implements a delta mutation operator meaning that for every gene in the genome a random number drawn from a normal distribution and it is added to the gene value according to a probability.
Specifically, the mutation delta is drawn from the Normal/Gaussian distribution with mean 0 and standard deviation defined by the argument variance.
Parameters
[in] genome The genome (genes) of an individual
Returns
A vector of floats (mutated genome)
Definition at line 71 of file mutation.cpp.
References delta(), mutation_rate, and variance.
Referenced by select_mutation_method().
discrete_crossover()
std::vector< REAL_ > GA::discrete_crossover (std::vector< REAL_ > parent1, std::vector< REAL_ > parent2)
Discrete crossover operator.
Performs a discrete crossover operation. Genes from both parent are combined in a random way, slightly different from uniform crossover. The second parent's genes replace genes from the first parent's genome in a random way. For each gene a random number {0, 1} is drawn and defines the replacement. In the case of a 0 being drawn, the second parent's gene replaces the first parent's gene.
Parameters
[in] parent1 First parent's genome
[in] parent2 Second parent's genome
Returns
Offspring's genome
Definition at line 240 of file crossover.cpp.
Referenced by select_crossover_method().
evaluation()
void GA::evaluation (std::vector< individual_s > & x)
Genetic Algorithm secondary operations.
Evaluates the fitness of each individual based on a predefined cost function.
Evaluation of fitness of individuals
Parameters
[in] x Vector of individuals (population)
Returns
Nothing (void)
See also
test_functions.cpp
Definition at line 189 of file genetic_alg.cpp.
References fitness.
Referenced by run_one_generation().
evolve()
void GA::evolve (size_t generations, size_t unique_id, pr_parameter_s * pms)
Main routine for evolving a population over generations.
Evolves a population based on previously defined operators.
Evolves a population of individuals based on operations such as selection, crossover, and mutation that have been predefined. It executes the
evolutionary step over the total number of generations. Finally, it prints out results either to STDOUT or to file.
Parameters
[in] generations Total number of generations
[in] unique_id Unique ID of a thread in case Island Model or Independent runs are used. Otherwise, can be any number of type size_t
[in] pms Structure of logging parameters
Returns
Nothing (void)
Definition at line 381 of file genetic_alg.cpp.
References best_individual, bsf, fit_avg, generations, individual::genome, population, parameter_pr::print_average_fitness, print_avg_fitness(), print_best_genome(), parameter_pr::print_best_genome, print_bsf(), parameter_pr::print_bsf, print_fitness(), parameter_pr::print_fitness, run_one_generation(), sort_population(), and parameter_pr::where2write.
Referenced by ga_optimization(), ga_optimization_python(), and independent_runs().
flat_crossover()
std::vector< REAL_ > GA::flat_crossover (std::vector< REAL_ > parent1, std::vector< REAL_ > parent2)
Flat crossover operator.
Performs a "flat" crossover operation. Genes from both parent are combined in as by linear mixing, similar to alpha blending. A random variate is chosen to specify
the mixing weight.
Parameters
[in] parent1 First parent's genome
[in] parent2 Second parent's genome
Returns
Offspring's genome
Definition at line 204 of file crossover.cpp.
Referenced by select_crossover_method().
fusion_mutation()
std::vector< REAL_ > GA::fusion_mutation (std::vector< REAL_ > genome)
Fusion mutation operator method.
Performs a fusion mutation operation. It checks if the genome has unique elements. If doesn't have, it removes the repetitions and replaces them by new random (uniformly drawn) values.
Parameters
[in] genome Individual's genome
Returns
A mutated genome.
Definition at line 189 of file mutation.cpp.
References is_real, low_bound, and up_bound.
Referenced by select_mutation_method().
get_average_fitness()
std::vector<REAL_>& GA::get_average_fitness () inline
Definition at line 331 of file gaim.h.
References fit_avg.
Referenced by ga_optimization(), and ga_optimization_python().
get_best_genome()
std::vector<REAL_>& GA::get_best_genome () inline
Definition at line 330 of file gaim.h.
References bsf_genome.
Referenced by ga_optimization(), and ga_optimization_python().
get_bsf()
std::vector<REAL_>& GA::get_bsf () inline
Definition at line 329 of file gaim.h.
References bsf.
Referenced by ga_optimization(), and ga_optimization_python().
ktournament_selection()
std::vector< individual_s > GA::ktournament_selection (std::vector< individual_s > & population)
Genetic Algorithm basic operators.
Implements a k-tournament selection.
Selection operator methods
Parameters
[in] population A vector of the entire population of individuals.
Returns
A vector of individual_s structures (selected parents).
Definition at line 71 of file selection.cpp.
References individual::fitness, individual::genome, k, num_parents, population, remove_at(), and replace.
Referenced by select_selection_method().
linear_rank_selection()
std::vector< individual_s > GA::linear_rank_selection (std::vector< individual_s > & population)
Implements a linear rank selection mechanism.
The population is sorted based on the fitness of each individual and then a selection probability is assigned to each individual based on their rank.
Parameters
[in] population A vector of the entire population of individuals replacement or not.
Returns
A vector of individual_s structures (or the selected parents).
Definition at line 192 of file selection.cpp.
References compare_fitness(), k, num_parents, population, and replace.
Referenced by select_selection_method().
next_generation()
void GA::next_generation (size_t perc = 3)
Generate the next generation out of current individuals and.
The basic operation for forming the next generation.
It determines which offspring individuals will pass their genomes to the next generation and which parents will be replaced. By default, it replaces the worst parents by the best offspring.
Parameters
[in] perc The percentage of old individuals that will be replaced by new individuals.
Returns
Nothing (void)
Note
The user can define his or her own method for the next generation.
Definition at line 224 of file genetic_alg.cpp.
References compare_fitness(), lambda, offsprings, and population.
Referenced by run_one_generation().
nonuniform_mutation()
std::vector< REAL_ > GA::nonuniform_mutation (std::vector< REAL_ > genome)
Non-uniform mutation operator.
Performs a non-uniform mutation which is time-dependent, decaying over time. The mutation is computed as or based on a random choice between -1 or 1, respectively.
Parameters
[in] genome Individual's genome
Returns
A mutated genome.
Definition at line 157 of file mutation.cpp.
References delta(), generations, low_bound, order, time, and up_bound.
Referenced by select_mutation_method().
one_point_crossover()
std::vector< REAL_ > GA::one_point_crossover (std::vector< REAL_ > parent1, std::vector< REAL_ > parent2)
Crossover operator methods.
Applies a crossover operator on the genomes of two parents (parent1 and parent2) to create a child genome.
By default, this is a one-point crossover operator.
Parameters
[in] parent1 Genome of the first parent
[in] parent2 Genome of the second parent
Returns
The genome of a child as a vector of type REAL_
Definition at line 74 of file crossover.cpp.
References order.
Referenced by select_crossover_method().
order_one_crossover()
std::vector< REAL_ > GA::order_one_crossover (std::vector< REAL_ > parent1, std::vector< REAL_ > parent2)
Order-one crossover operator.
Performs an order-one crossover operation. It starts from the half genome of the first parent and as long as the genes between the two parents are different, it copies parent 2's genes to the child's genome.
Note
This operator is useful in problems involving permuations. The rule is somewhat different from traditional single-point crossover, which has no guarantees of preserving parent A's half genome.
Parameters
[in] parent1 First parent's genome
[in] parent2 Second parent's genome
Returns
Offspring's genome
Definition at line 280 of file crossover.cpp.
Referenced by select_crossover_method().
random_mutation()
std::vector< REAL_ > GA::random_mutation (std::vector< REAL_ > genome)
Random mutation operator.
Performs a random mutation on the genome of an individual. A random mutation takes place at a random gene and replaces the current value of the gene with a new random one drawn from a uniform distribution in the interval [a, b].
Parameters
[in] genome Individual's genome (genes)
Returns
A mutated genome (vector of type REAL_).
Definition at line 99 of file mutation.cpp.
References is_real, low_bound, and up_bound.
Referenced by select_mutation_method().
random_selection()
std::vector< individual_s > GA::random_selection (std::vector< individual_s > & population)
Implements a random selection.
It randomly picks up one individual from the entire population.
Parameters
[in] population A vector of the entire population of individuals.
Returns
A vector of indivudual_s as parents.
Definition at line 260 of file selection.cpp.
References int_random(), num_parents, population, and replace.
Referenced by select_selection_method().
reset_selection_flags()
void GA::reset_selection_flags ()
Reset the flag is_selected (used from selections methods when.
Resets selection flags.
A selection flags indicate if an individual has been selected to procreate from any selection method. This method has to be used only when replace is set to true in selection method.
Parameters
[in] (void)
Returns
Nothing (void)
Warning
This methods has to be called after the method next_generation and only when a selection operator without replacement has been chosen.
Definition at line 252 of file genetic_alg.cpp.
References population.
Referenced by run_one_generation().
roulette_wheel_selection()
std::vector< individual_s > GA::roulette_wheel_selection (std::vector< individual_s > & population)
Implements a roulette-wheel selection (or fitness-proportionate selection) mechanism.
The fitness function observes a fitness for each individual and the share of the population's total fitness is used to associate a selection
probability with each individual.
Parameters
[in] population A vector of the entire population of individuals.
Returns
A vector of individual_s which corresponds to the selected parents.
Definition at line 308 of file selection.cpp.
References average_fitness(), cumulative_fitness(), float_random(), num_parents, population, and replace.
Referenced by select_selection_method().
run_one_generation()
void GA::run_one_generation (void)
Main routine for running one single generation step.
One single step of evolution (this is the main GA algorithm).
Runs one step of evolution. This means that this method evaluates and sorts a population of individuals. It then selects parents, crosses and mutates their genomes, and generates the proper amount of offspring. Then it replaces the old generation with a new one.
Parameters
[in] (void)
Returns
Nothing (void)
Definition at line 295 of file genetic_alg.cpp.
References average_fitness(), best_individual, bsf, bsf_genome, clip_genome(), crossover, evaluation(), fit_avg, individual::fitness, fitness, individual::genome, hfi, lambda, lfi, mu, mutation, next_generation(), offsprings, population, replace_perc, reset_selection_flags(), selection, sort_population(), and sorted_population.
Referenced by evolve().
select_crossover_method()
void GA::select_crossover_method (void)
This method assigns the appropriate crossover method to crossover pointer function.
Assigns the appropriate crossover operator to the pointer function *crossover.
This method assigns to the crossover operator (pointer function) the appropriate method based on the crossover method string. The crossover method is provided by the data structure cross_parameter_s.
Parameters
[in] void
Returns
Nothing
See also
cross_parameter_s
Definition at line 45 of file crossover.cpp.
References crossover, crossover_method, discrete_crossover(), flat_crossover(), one_point_crossover(), order_one_crossover(), two_point_crossover(), and uniform_crossover().
Referenced by GA().
select_mutation_method()
void GA::select_mutation_method (void)
This method assigns the appropriate mutation operator based on the chosen mutation method.
Assigns the appropriate mutation operator to the pointer function *mutation.
This method assigns to the mutation operator (pointer function) the appropriate method based on the mutation method string. The mutation method is provided by the data structure mut_parameter_s.
Parameters
[in] void
Returns
Nothing
See also
mut_parameter_s
Definition at line 43 of file mutation.cpp.
References delta_mutation(), fusion_mutation(), mutation, mutation_method, nonuniform_mutation(), random_mutation(), and swap_mutation().
Referenced by GA().
select_selection_method()
void GA::select_selection_method (void)
This method assigns the appropriate selection method to selection pointer function.
Assigns the appropriate selection operator to the pointer function *selection.
This method assigns to the selection operator (pointer function) the appropriate method based on the selection method string. The selection method is provided by the data structure sel_parameter_s.
Parameters
[in] void
Returns
Nothing
See also
sel_parameter_s
Definition at line 42 of file selection.cpp.
References ktournament_selection(), linear_rank_selection(), random_selection(), roulette_wheel_selection(), selection, selection_method, stochastic_roulette_wheel_selection(), truncation_selection(), and whitley_selection().
Referenced by GA().
sort_population()
void GA::sort_population (void)
Sorting individuals based on their fitness value.
Sorts the individuals within a population based on their fitness value.
Parameters
void
Returns
Nothing (void)
Definition at line 203 of file genetic_alg.cpp.
References compare_fitness(), population, and sorted_population.
Referenced by evolve(), and run_one_generation().
stochastic_roulette_wheel_selection()
std::vector< individual_s > GA::stochastic_roulette_wheel_selection (std::vector< individual_s > & population)
Parent selection method proposed by Lipowski A.
and Lipowska D. in "Roulette wheel selection via stochastic acceptance", 2011. The method is a variant of the roulette wheel where the maximum fitness is used to normalize individuals' fitness and transform them to a probability. The latter is used to decide probabilisticly if the chosen individual will be allowed to get offsprings.
Parameters
[in] population A vector of the entire population of individuals.
Returns
A vector of indivudual_s (selected parents).
Definition at line 380 of file selection.cpp.
References float_random(), int_random(), maximum_fitness(), nonselected_maximum_fitness(), num_parents, population, remove_at(), and replace.
Referenced by select_selection_method().
swap_mutation()
std::vector< REAL_ > GA::swap_mutation (std::vector< REAL_ > genome)
Swap mutation operator method.
Performs a swap mutation operation. It randomly picks up two genes on the same genome and swaps them.
Note
The swap mutation operator is useful in cases of permutations (for instance in solving problems such as the Traveling Salesman Problem).
Parameters
[in] genome Individual's genome
Returns
A mutated genome.
Definition at line 234 of file mutation.cpp.
Referenced by select_mutation_method().
truncation_selection()
std::vector< individual_s > GA::truncation_selection (std::vector< individual_s > & population)
Implements a truncation selection operator.
The population is sorted based on the fitness of each individual and a percentage of individuals that will be discarded is computed based on the given number of offsprings (lambda).
Parameters
[in] population A vector of the entire population of individuals
Returns
A vector of individual_s structures (or the selected parents).
Definition at line 136 of file selection.cpp.
References compare_fitness(), int_random(), lower_bound, mu, num_parents, population, and replace.
Referenced by select_selection_method().
two_point_crossover()
std::vector< REAL_ > GA::two_point_crossover (std::vector< REAL_ > parent1, std::vector< REAL_ > parent2)
Two-point crossover operator.
Performs a two-point crossover. Two random points on the genome are drawn from a uniform distribution and the genes within the
area defined by the two points is swapped between parents.
Parameters
[in] parent1 First parent's genome
[in] parent2 Second parent's genome
Returns
Offspring's genome
Definition at line 115 of file crossover.cpp.
References order.
Referenced by select_crossover_method().
uniform_crossover()
std::vector< REAL_ > GA::uniform_crossover (std::vector< REAL_ > parent1, std::vector< REAL_ > parent2)
Uniform crossover operator.
Performs a uniform crossover operation. Each gene is chosen from one parent or the other with equal probability.
Parameters
[in] parent1 First parent's genome
[in] parent2 Second parent's genome
Returns
Offspring's genome
Definition at line 163 of file crossover.cpp.
References order.
Referenced by select_crossover_method().
whitley_selection()
std::vector< individual_s > GA::whitley_selection (std::vector< individual_s > & population)
Parent selection method proposed by Darrell Whitley in his GENITOR paper: "The GENITOR Algorithm and Selection Pressure: Why Rank-Based Allocation of Reproductive Trials is Best", ", D.
Whitley, 2000.
Parameters
[in] population A vector of the entire population of individuals.
Returns
A vector of indivudual_s (selected parents).
See also
calculate_whitley_factor() On how to calculate the Whitley factor.
Definition at line 461 of file selection.cpp.
References bias, calculate_whitley_factor(), num_parents, population, and replace.
Referenced by select_selection_method().
Friends And Related Function Documentation
IM
friend class IM friend
Definition at line 368 of file gaim.h.
Member Data Documentation
alpha
std::vector<REAL_> GA::alpha private
BSF genome.
Definition at line 345 of file gaim.h.
Referenced by GA().
best_individual
individual_s GA::best_individual
Sorted population vector.
Definition at line 337 of file gaim.h.
Referenced by evolve(), and run_one_generation().
beta
std::vector<REAL_> GA::beta private
Definition at line 345 of file gaim.h.
Referenced by GA().
bias
REAL_ GA::bias private
Definition at line 350 of file gaim.h.
Referenced by pygaim.pygaim.GAOptimize::fit(), GA(), and whitley_selection().
bsf
std::vector<REAL_> GA::bsf
Best individual (keep track)
Definition at line 338 of file gaim.h.
Referenced by evolve(), pygaim.pygaim.GAOptimize::fit(), get_bsf(), pygaim.pygaim.GAOptimize::plot_(), and run_one_generation().
bsf_genome
std::vector<REAL_> GA::bsf_genome
Lowest fitness in the population.
Definition at line 342 of file gaim.h.
Referenced by get_best_genome(), and run_one_generation().
crossover
std::vector<REAL_>(GA::* GA::crossover) (std::vector< REAL_ >, std::vector< REAL_ >)
Crossover pointer function.
Definition at line 287 of file gaim.h.
Referenced by run_one_generation(), and select_crossover_method().
crossover_method
std::string GA::crossover_method private
Definition at line 348 of file gaim.h.
Referenced by pygaim.pygaim.GAOptimize::fit(), GA(), and select_crossover_method().
fit_avg
std::vector<REAL_> GA::fit_avg
BSF vector (keep track)
Definition at line 339 of file gaim.h.
Referenced by evolve(), get_average_fitness(), and run_one_generation().
fitness
REAL_(* GA::fitness) (REAL_ *, size_t)
Definition at line 332 of file gaim.h.
Referenced by evaluation(), GA(), ga_optimization(), ga_optimization_python(), and run_one_generation().
generations
size_t GA::generations private
Definition at line 362 of file gaim.h.
Referenced by evolve(), and nonuniform_mutation().
genome_size
size_t GA::genome_size private
Number of individuals being replaced.
Definition at line 358 of file gaim.h.
Referenced by pygaim.pygaim.GAOptimize::fit(), and GA().
hfi
std::vector<REAL_> GA::hfi
Average fitness vector (keep track)
Definition at line 340 of file gaim.h.
Referenced by run_one_generation().
immigrant
std::vector<individual_s> GA::immigrant private
Genome's interval limits [a, b].
Definition at line 346 of file gaim.h.
is_real
bool GA::is_real private
If replace is enabled, then selected parents are replaced.
Definition at line 366 of file gaim.h.
Referenced by pygaim.pygaim.GAOptimize::fit(), fusion_mutation(), GA(), and random_mutation().
k
int GA::k private
Definition at line 364 of file gaim.h.
Referenced by pygaim.pygaim.GAOptimize::fit(), GA(), ktournament_selection(), and linear_rank_selection().
lambda
size_t GA::lambda private
Number of individuals within a population.
Definition at line 356 of file gaim.h.
Referenced by GA(), next_generation(), and run_one_generation().
lfi
std::vector<REAL_> GA::lfi
Highest fitness in the population.
Definition at line 341 of file gaim.h.
Referenced by run_one_generation().
low_bound
REAL_ GA::low_bound private
Definition at line 353 of file gaim.h.
Referenced by pygaim.pygaim.GAOptimize::fit(), fusion_mutation(), GA(), nonuniform_mutation(), and random_mutation().
lower_bound
size_t GA::lower_bound private
Number of parents per generation to select from.
Definition at line 360 of file gaim.h.
Referenced by pygaim.pygaim.GAOptimize::fit(), GA(), and truncation_selection().
mu
size_t GA::mu private
Definition at line 355 of file gaim.h.
Referenced by GA(), run_one_generation(), and truncation_selection().
mutation
std::vector<REAL_>(GA::* GA::mutation) (std::vector< REAL_ >)
Mutation pointer function.
Definition at line 301 of file gaim.h.
Referenced by run_one_generation(), and select_mutation_method().
mutation_method
std::string GA::mutation_method private
Definition at line 349 of file gaim.h.
Referenced by pygaim.pygaim.GAOptimize::fit(), GA(), and select_mutation_method().
mutation_rate
REAL_ GA::mutation_rate private
Bias term for Whitley selection metehod.
Definition at line 351 of file gaim.h.
Referenced by delta_mutation(), pygaim.pygaim.GAOptimize::fit(), and GA().
num_parents
size_t GA::num_parents private
Genome size (number of genes)
Definition at line 359 of file gaim.h.
Referenced by pygaim.pygaim.GAOptimize::fit(), GA(), ktournament_selection(), linear_rank_selection(), random_selection(), roulette_wheel_selection(), stochastic_roulette_wheel_selection(), truncation_selection(), and whitley_selection().
offsprings
std::vector<individual_s> GA::offsprings
Individuals population vector.
Definition at line 335 of file gaim.h.
Referenced by GA(), next_generation(), run_one_generation(), and ~GA().
order
size_t GA::order private
Definition at line 363 of file gaim.h.
Referenced by pygaim.pygaim.GAOptimize::fit(), GA(), nonuniform_mutation(), one_point_crossover(), two_point_crossover(), and uniform_crossover().
population
std::vector<individual_s> GA::population
Definition at line 334 of file gaim.h.
Referenced by clip_genome(), evolve(), GA(), ktournament_selection(), linear_rank_selection(), next_generation(), random_selection(), reset_selection_flags(), roulette_wheel_selection(), run_one_generation(), sort_population(), stochastic_roulette_wheel_selection(), truncation_selection(), whitley_selection(), and ~GA().
replace
bool GA::replace private
k-tournament order
Definition at line 365 of file gaim.h.
Referenced by pygaim.pygaim.GAOptimize::fit(), GA(), ktournament_selection(), linear_rank_selection(), random_selection(), roulette_wheel_selection(), stochastic_roulette_wheel_selection(), truncation_selection(), and whitley_selection().
replace_perc
size_t GA::replace_perc private
Number of offsprings.
Definition at line 357 of file gaim.h.
Referenced by GA(), and run_one_generation().
selection
std::vector<individual_s>(GA::* GA::selection) (std::vector< individual_s > &)
Selection pointer function.
Definition at line 272 of file gaim.h.
Referenced by run_one_generation(), and select_selection_method().
selection_method
std::string GA::selection_method private
Immigrants vector (buffer)
Definition at line 347 of file gaim.h.
Referenced by pygaim.pygaim.GAOptimize::fit(), GA(), and select_selection_method().
sorted_population
std::vector<individual_s> GA::sorted_population
Offsprings vector.
Definition at line 336 of file gaim.h.
Referenced by GA(), run_one_generation(), sort_population(), and ~GA().
time
size_t GA::time private
Starting index for truncation selection.
Definition at line 361 of file gaim.h.
Referenced by GA(), and nonuniform_mutation().
up_bound
REAL_ GA::up_bound private
Definition at line 354 of file gaim.h.
Referenced by pygaim.pygaim.GAOptimize::fit(), fusion_mutation(), GA(), nonuniform_mutation(), and random_mutation().
variance
REAL_ GA::variance private
Definition at line 352 of file gaim.h.
Referenced by delta_mutation(), and GA().
The documentation for this class was generated from the following files:
gaim.h
crossover.cpp
genetic_alg.cpp
mutation.cpp
selection.cpp