Project GAIM: IM Class Reference
IM Class Reference
Island Model main class.
#include <gaim.h>
Public Member Functions
IM (im_parameter_s *, ga_parameter_s *)
Constructor of Island Model (IM) class.
~IM ()
IM Constructor method.
void select_ind2migrate (size_t, size_t, std::string method="random")
IM Destructor method.
void move_immigrants (size_t, size_t, std::string)
Immigration method. It moves the immigrants (individuals) from one.
size_t read_connectivity_graph (std::string)
Island Model secondary operations methods.
void evolve_island (size_t, im_parameter_s *, pr_parameter_s *)
Evolves an island (thread function)
void run_islands (im_parameter_s *, pr_parameter_s *)
Runs the Island Models.
Public Attributes
std::vector< GA > island
Private Attributes
std::vector< REAL_ > a
Islands (threads) vector.
std::vector< REAL_ > b
std::map< int, std::vector< int > > adj_list
Genome's interval [a, b].
size_t generations
Adjacent list of islands.
size_t num_immigrants
Generations.
size_t num_islands
Number of immigrants.
size_t migration_interval
Number of islands (threads)
size_t migration_steps
Migration interval.
std::mutex mtx
Generations / Migration Interval.
Detailed Description
Island Model main class.
Island Model class contains methods to run an Island Model (IM) optimization. The class instance reads the topology from a file and builds a map (adjacency list). Moreover, provides methods for individuals selection and immigration over islands (threads).
Definition at line 248 of file gaim.h.
Constructor & Destructor Documentation
IM()
IM::IM (im_parameter_s * im_pms, ga_parameter_s * ga_pms)
Constructor of Island Model (IM) class.
Initializes all the necessary parameters and vectors for running an Island Model and evolve different islands (threads) based on a predermined Genetic Algorithm (GA).
Parameters
[in] im_pms Structure of IM parameters
[in] ga_pms Structure of GA parameters
Returns
Nothing
Definition at line 47 of file island_ga.cpp.
References parameter_ga::a, a, parameter_im::adj_list_fname, parameter_ga::b, b, parameter_ga::generations, island, parameter_im::migration_interval, migration_interval, migration_steps, parameter_im::num_immigrants, num_immigrants, parameter_im::num_islands, num_islands, and read_connectivity_graph().
~IM()
IM::~IM ()
IM Constructor method.
Destructor of IM class.
Definition at line 86 of file island_ga.cpp.
References adj_list, and island.
Member Function Documentation
evolve_island()
void IM::evolve_island (size_t unique_id, im_parameter_s * im_pms, pr_parameter_s * pr_pms)
Evolves an island (thread function)
Evolves an island.
This method runs the genetic algorithm per island and performs two major operations, selection of outgoing individuals (migrants) and replacement of the target population. Furthermore, it provides logging for the results of the evolution process per island.
Parameters
unique_id Unique ID number of island (thread ID)
im_pms Island model parameters structure
pr_pms Logging parameters structure
Returns
Nothing (void)
Definition at line 288 of file island_ga.cpp.
References barrier, island, migration_interval, migration_steps, move_immigrants(), mtx, parameter_im::num_immigrants, parameter_im::num_islands, parameter_im::pick_method, parameter_pr::print_average_fitness, print_avg_fitness(), parameter_pr::print_best_genome, print_best_genome(), print_bsf(), parameter_pr::print_bsf, print_fitness(), parameter_pr::print_fitness, parameter_im::replace_method, select_ind2migrate(), and parameter_pr::where2write.
Referenced by PYBIND11_MODULE(), and run_islands().
move_immigrants()
void IM::move_immigrants (size_t num_immigrants, size_t unique_id, std::string method = "random")
Immigration method. It moves the immigrants (individuals) from one.
Moves immigrants from one island (thread) to another based on a predefined method.
Supported methods are:
random Individuals from the current island are randomly chosen and they are replaced by immigrants
elit The highest-fitness individuals within the current island population are replaced by immigrants
poor The lowest-fitness individuals within the current island population are replaced by immigrants
Parameters
num_immigrants Total number of immigrants the island can accept
unique_id Island's unique ID (thread ID)
method How individuals from the local population will be replaced by immigrants
Returns
Nonthing (void)
Note
In a future version of GAIM, islands will support a variable number of immigrants.
Definition at line 225 of file island_ga.cpp.
References adj_list, island, mtx, num_immigrants, and pcg_extras::shuffle().
Referenced by evolve_island(), and PYBIND11_MODULE().
read_connectivity_graph()
size_t IM::read_connectivity_graph (std::string fname)
Island Model secondary operations methods.
Reads the connectivity graph (topology) from a text file.
Reads the connectivity graph (topology) from a file
The graph defines the number of islands (run on separate threads) and how they are connected. The format of the file is as follows: XX (number of islands - vertices) DST #edges SRC1 SRC2 SRC3
Example (ring topology with four islands): 4 0 1 3 1 1 0 2 1 1 3 1 2
Parameters
[in] fname The name of the file that contains the graph
Returns
num_vertices The number of vertices (islands) found in the file.
Note
The number of vertices is returned in order to validate the number of islands. In the rest of the code if the number if islands provided by the user does not match the number of vertices then the latter is being used as number of islands (threads).
Definition at line 115 of file island_ga.cpp.
References adj_list, and num_islands.
Referenced by IM(), and PYBIND11_MODULE().
run_islands()
void IM::run_islands (im_parameter_s * im_pms, pr_parameter_s * pr_pms)
Runs the Island Models.
Runs an Island Model experiment.
Parameters
im_pms Island model parameters structure
pr_pms Logging parameters structure
Returns
Nothing (void)
Definition at line 343 of file island_ga.cpp.
References barrier, evolve_island(), parameter_im::num_islands, and num_islands.
Referenced by ga_optimization(), and PYBIND11_MODULE().
select_ind2migrate()
void IM::select_ind2migrate (size_t num_immigrants, size_t unique_id, std::string method = "random")
IM Destructor method.
Selects the candidate individuals for immigration.
Island Model basic operators methods Selection method. It selects individuals per island to move and
The current method implements three distinct selection methods.
random The number of individuals is selected randomly from the population
elit Individuals with the best fitness (elit) are selected
poor Individuals with the worst fitness (poor) are selected
Parameters
num_immigrants Number of total individuals who are selected to migrate
unique_id Is the unique ID of each island (thread ID)
method Defines whith strategy (policy) of selecting individuals is going to be used (elit, poor, random)
Returns
Nothing (void)
Note
In a future version of GAIM, each island will accept a different number of immigrants.
Definition at line 162 of file island_ga.cpp.
References a, b, island, mtx, num_immigrants, and pcg_extras::shuffle().
Referenced by evolve_island(), and PYBIND11_MODULE().
Member Data Documentation
a
std::vector<REAL_> IM::a private
Islands (threads) vector.
Definition at line 278 of file gaim.h.
Referenced by IM(), and select_ind2migrate().
adj_list
std::map<int, std::vector<int> > IM::adj_list private
Genome's interval [a, b].
Definition at line 279 of file gaim.h.
Referenced by move_immigrants(), read_connectivity_graph(), and ~IM().
b
std::vector<REAL_> IM::b private
Definition at line 278 of file gaim.h.
Referenced by IM(), and select_ind2migrate().
generations
size_t IM::generations private
Adjacent list of islands.
Definition at line 280 of file gaim.h.
island
std::vector<GA> IM::island
Definition at line 275 of file gaim.h.
Referenced by evolve_island(), ga_optimization(), IM(), move_immigrants(), select_ind2migrate(), and ~IM().
migration_interval
size_t IM::migration_interval private
Number of islands (threads)
Definition at line 283 of file gaim.h.
Referenced by evolve_island(), and IM().
migration_steps
size_t IM::migration_steps private
Migration interval.
Definition at line 284 of file gaim.h.
Referenced by evolve_island(), and IM().
mtx
std::mutex IM::mtx private
Generations / Migration Interval.
Definition at line 286 of file gaim.h.
Referenced by evolve_island(), move_immigrants(), and select_ind2migrate().
num_immigrants
size_t IM::num_immigrants private
Generations.
Definition at line 281 of file gaim.h.
Referenced by IM(), move_immigrants(), and select_ind2migrate().
num_islands
size_t IM::num_islands private
Number of immigrants.
Definition at line 282 of file gaim.h.
Referenced by IM(), read_connectivity_graph(), and run_islands().
The documentation for this class was generated from the following files:
gaim.h
island_ga.cpp