Project GAIM: pcg_detail::extended< table_pow2, advance_pow2, baseclass, extvalclass, kdd > Class Template Reference
pcg_detail::extended< table_pow2, advance_pow2, baseclass, extvalclass, kdd > Class Template Reference
#include <pcg_random.hpp>
Public Types
typedef baseclass::state_type state_type
typedef baseclass::result_type result_type
typedef inside_out< extvalclass > insideout
Public Member Functions
__attribute__ ((always_inline)) result_type operator()()
result_type operator() (result_type upper_bound)
void set (result_type wanted)
void advance (state_type distance, bool forwards=true)
void backstep (state_type distance)
extended (const result_type *data)
extended (const result_type *data, state_type seed)
template<typename bc = baseclass>
extended (const result_type *data, state_type seed, typename bc::stream_state stream_seed)
extended ()
extended (state_type seed)
template<typename bc = baseclass>
extended (state_type seed, typename bc::stream_state stream_seed)
template<typename SeedSeq , typename = typename std::enable_if< !std::is_convertible<SeedSeq, result_type>::value && !std::is_convertible<SeedSeq, extended>::value>::type>
extended (SeedSeq &&seedSeq)
template<typename... Args>
void seed (Args &&... args)
Static Public Member Functions
static constexpr size_t period_pow2 ()
Private Member Functions
PCG_NOINLINE void advance_table ()
PCG_NOINLINE void advance_table (state_type delta, bool isForwards=true)
result_type & get_extended_value ()
void selfinit ()
void datainit (const result_type *data)
Private Attributes
result_type data_ [table_size]
Static Private Attributes
static constexpr bitcount_t rtypebits = sizeof(result_type)*8
static constexpr bitcount_t stypebits = sizeof(state_type)*8
static constexpr bitcount_t tick_limit_pow2 = 64U
static constexpr size_t table_size = 1UL << table_pow2
static constexpr size_t table_shift = stypebits - table_pow2
static constexpr state_type table_mask
static constexpr bool may_tick
static constexpr size_t tick_shift = stypebits - advance_pow2
static constexpr state_type tick_mask
static constexpr bool may_tock = stypebits < tick_limit_pow2
Friends
template<bitcount_t table_pow2_, bitcount_t advance_pow2_, typename baseclass_ , typename extvalclass_ , bool kdd_>
bool operator== (const extended< table_pow2_, advance_pow2_, baseclass_, extvalclass_, kdd_ > &, const extended< table_pow2_, advance_pow2_, baseclass_, extvalclass_, kdd_ > &)
template<typename CharT , typename Traits , bitcount_t table_pow2_, bitcount_t advance_pow2_, typename baseclass_ , typename extvalclass_ , bool kdd_>
std::basic_ostream< CharT, Traits > & operator<< (std::basic_ostream< CharT, Traits > &out, const extended< table_pow2_, advance_pow2_, baseclass_, extvalclass_, kdd_ > &)
template<typename CharT , typename Traits , bitcount_t table_pow2_, bitcount_t advance_pow2_, typename baseclass_ , typename extvalclass_ , bool kdd_>
std::basic_istream< CharT, Traits > & operator>> (std::basic_istream< CharT, Traits > &in, extended< table_pow2_, advance_pow2_, baseclass_, extvalclass_, kdd_ > &)
Detailed Description
template<bitcount_t table_pow2, bitcount_t advance_pow2, typename baseclass, typename extvalclass, bool kdd = true>
class pcg_detail::extended< table_pow2, advance_pow2, baseclass, extvalclass, kdd >
Definition at line 1142 of file pcg_random.hpp.
Member Typedef Documentation
insideout
template<bitcount_t table_pow2, bitcount_t advance_pow2, typename baseclass , typename extvalclass , bool kdd = true> typedef inside_out<extvalclass> pcg_detail::extended< table_pow2, advance_pow2, baseclass, extvalclass, kdd >::insideout
Definition at line 1146 of file pcg_random.hpp.
result_type
template<bitcount_t table_pow2, bitcount_t advance_pow2, typename baseclass , typename extvalclass , bool kdd = true> typedef baseclass::result_type pcg_detail::extended< table_pow2, advance_pow2, baseclass, extvalclass, kdd >::result_type
Definition at line 1145 of file pcg_random.hpp.
state_type
template<bitcount_t table_pow2, bitcount_t advance_pow2, typename baseclass , typename extvalclass , bool kdd = true> typedef baseclass::state_type pcg_detail::extended< table_pow2, advance_pow2, baseclass, extvalclass, kdd >::state_type
Definition at line 1144 of file pcg_random.hpp.
Constructor & Destructor Documentation
extended() [1/7]
template<bitcount_t table_pow2, bitcount_t advance_pow2, typename baseclass , typename extvalclass , bool kdd = true> pcg_detail::extended< table_pow2, advance_pow2, baseclass, extvalclass, kdd >::extended (const result_type * data) inline
Definition at line 1232 of file pcg_random.hpp.
extended() [2/7]
template<bitcount_t table_pow2, bitcount_t advance_pow2, typename baseclass , typename extvalclass , bool kdd = true> pcg_detail::extended< table_pow2, advance_pow2, baseclass, extvalclass, kdd >::extended (const result_type * data, state_type seed) inline
Definition at line 1238 of file pcg_random.hpp.
extended() [3/7]
template<bitcount_t table_pow2, bitcount_t advance_pow2, typename baseclass , typename extvalclass , bool kdd = true> template<typename bc = baseclass> pcg_detail::extended< table_pow2, advance_pow2, baseclass, extvalclass, kdd >::extended (const result_type * data, state_type seed, typename bc::stream_state stream_seed) inline
Definition at line 1248 of file pcg_random.hpp.
extended() [4/7]
template<bitcount_t table_pow2, bitcount_t advance_pow2, typename baseclass , typename extvalclass , bool kdd = true> pcg_detail::extended< table_pow2, advance_pow2, baseclass, extvalclass, kdd >::extended () inline
Definition at line 1255 of file pcg_random.hpp.
extended() [5/7]
template<bitcount_t table_pow2, bitcount_t advance_pow2, typename baseclass , typename extvalclass , bool kdd = true> pcg_detail::extended< table_pow2, advance_pow2, baseclass, extvalclass, kdd >::extended (state_type seed) inline
Definition at line 1261 of file pcg_random.hpp.
extended() [6/7]
template<bitcount_t table_pow2, bitcount_t advance_pow2, typename baseclass , typename extvalclass , bool kdd = true> template<typename bc = baseclass> pcg_detail::extended< table_pow2, advance_pow2, baseclass, extvalclass, kdd >::extended (state_type seed, typename bc::stream_state stream_seed) inline
Definition at line 1271 of file pcg_random.hpp.
extended() [7/7]
template<bitcount_t table_pow2, bitcount_t advance_pow2, typename baseclass , typename extvalclass , bool kdd = true> template<typename SeedSeq , typename = typename std::enable_if< !std::is_convertible<SeedSeq, result_type>::value && !std::is_convertible<SeedSeq, extended>::value>::type> pcg_detail::extended< table_pow2, advance_pow2, baseclass, extvalclass, kdd >::extended (SeedSeq && seedSeq) inline
Definition at line 1286 of file pcg_random.hpp.
Member Function Documentation
__attribute__()
template<bitcount_t table_pow2, bitcount_t advance_pow2, typename baseclass , typename extvalclass , bool kdd = true> pcg_detail::extended< table_pow2, advance_pow2, baseclass, extvalclass, kdd >::__attribute__ ((always_inline)) inline
Definition at line 1206 of file pcg_random.hpp.
advance()
template<bitcount_t table_pow2, bitcount_t advance_pow2, typename baseclass , typename extvalclass , bool kdd> void pcg_detail::extended< table_pow2, advance_pow2, baseclass, extvalclass, kdd >::advance (state_type distance, bool forwards = true)
Definition at line 1476 of file pcg_random.hpp.
References distance().
advance_table() [1/2]
template<bitcount_t table_pow2, bitcount_t advance_pow2, typename baseclass , typename extvalclass , bool kdd> void pcg_detail::extended< table_pow2, advance_pow2, baseclass, extvalclass, kdd >::advance_table private
Definition at line 1435 of file pcg_random.hpp.
advance_table() [2/2]
template<bitcount_t table_pow2, bitcount_t advance_pow2, typename baseclass , typename extvalclass , bool kdd> void pcg_detail::extended< table_pow2, advance_pow2, baseclass, extvalclass, kdd >::advance_table (state_type delta, bool isForwards = true) private
Definition at line 1450 of file pcg_random.hpp.
References delta().
backstep()
template<bitcount_t table_pow2, bitcount_t advance_pow2, typename baseclass , typename extvalclass , bool kdd = true> void pcg_detail::extended< table_pow2, advance_pow2, baseclass, extvalclass, kdd >::backstep (state_type distance) inline
Definition at line 1227 of file pcg_random.hpp.
References distance().
datainit()
template<bitcount_t table_pow2, bitcount_t advance_pow2, typename baseclass , typename extvalclass , bool kdd> void pcg_detail::extended< table_pow2, advance_pow2, baseclass, extvalclass, kdd >::datainit (const result_type * data) private
Definition at line 1326 of file pcg_random.hpp.
get_extended_value()
template<bitcount_t table_pow2, bitcount_t advance_pow2, typename baseclass , typename extvalclass , bool kdd = true> result_type& pcg_detail::extended< table_pow2, advance_pow2, baseclass, extvalclass, kdd >::get_extended_value () inline private
Definition at line 1176 of file pcg_random.hpp.
operator()()
template<bitcount_t table_pow2, bitcount_t advance_pow2, typename baseclass , typename extvalclass , bool kdd = true> result_type pcg_detail::extended< table_pow2, advance_pow2, baseclass, extvalclass, kdd >::operator() (result_type upper_bound) inline
Definition at line 1213 of file pcg_random.hpp.
References pcg_extras::bounded_rand().
period_pow2()
template<bitcount_t table_pow2, bitcount_t advance_pow2, typename baseclass , typename extvalclass , bool kdd = true> static constexpr size_t pcg_detail::extended< table_pow2, advance_pow2, baseclass, extvalclass, kdd >::period_pow2 () inline static constexpr
Definition at line 1201 of file pcg_random.hpp.
seed()
template<bitcount_t table_pow2, bitcount_t advance_pow2, typename baseclass , typename extvalclass , bool kdd = true> template<typename... Args> void pcg_detail::extended< table_pow2, advance_pow2, baseclass, extvalclass, kdd >::seed (Args &&... args) inline
Definition at line 1293 of file pcg_random.hpp.
selfinit()
template<bitcount_t table_pow2, bitcount_t advance_pow2, typename baseclass , typename extvalclass , bool kdd> void pcg_detail::extended< table_pow2, advance_pow2, baseclass, extvalclass, kdd >::selfinit private
Definition at line 1335 of file pcg_random.hpp.
set()
template<bitcount_t table_pow2, bitcount_t advance_pow2, typename baseclass , typename extvalclass , bool kdd = true> void pcg_detail::extended< table_pow2, advance_pow2, baseclass, extvalclass, kdd >::set (result_type wanted) inline
Definition at line 1218 of file pcg_random.hpp.
Friends And Related Function Documentation
operator<<
template<bitcount_t table_pow2, bitcount_t advance_pow2, typename baseclass , typename extvalclass , bool kdd = true> template<typename CharT , typename Traits , bitcount_t table_pow2_, bitcount_t advance_pow2_, typename baseclass_ , typename extvalclass_ , bool kdd_> std::basic_ostream<CharT,Traits>& operator<< (std::basic_ostream< CharT, Traits > & out, const extended< table_pow2_, advance_pow2_, baseclass_, extvalclass_, kdd_ > &) friend
operator==
template<bitcount_t table_pow2, bitcount_t advance_pow2, typename baseclass , typename extvalclass , bool kdd = true> template<bitcount_t table_pow2_, bitcount_t advance_pow2_, typename baseclass_ , typename extvalclass_ , bool kdd_> bool operator== (const extended< table_pow2_, advance_pow2_, baseclass_, extvalclass_, kdd_ > & , const extended< table_pow2_, advance_pow2_, baseclass_, extvalclass_, kdd_ > &) friend
operator>>
template<bitcount_t table_pow2, bitcount_t advance_pow2, typename baseclass , typename extvalclass , bool kdd = true> template<typename CharT , typename Traits , bitcount_t table_pow2_, bitcount_t advance_pow2_, typename baseclass_ , typename extvalclass_ , bool kdd_> std::basic_istream<CharT,Traits>& operator>> (std::basic_istream< CharT, Traits > & in, extended< table_pow2_, advance_pow2_, baseclass_, extvalclass_, kdd_ > &) friend
Member Data Documentation
data_
template<bitcount_t table_pow2, bitcount_t advance_pow2, typename baseclass , typename extvalclass , bool kdd = true> result_type pcg_detail::extended< table_pow2, advance_pow2, baseclass, extvalclass, kdd >::data_[table_size] private
Definition at line 1170 of file pcg_random.hpp.
Referenced by pcg_detail::operator>>().
may_tick
template<bitcount_t table_pow2, bitcount_t advance_pow2, typename baseclass , typename extvalclass , bool kdd = true> constexpr bool pcg_detail::extended< table_pow2, advance_pow2, baseclass, extvalclass, kdd >::may_tick static constexpr private
Initial value:
=
        (advance_pow2 < stypebits) && (advance_pow2 < tick_limit_pow2)
Definition at line 1159 of file pcg_random.hpp.
may_tock
template<bitcount_t table_pow2, bitcount_t advance_pow2, typename baseclass , typename extvalclass , bool kdd = true> constexpr bool pcg_detail::extended< table_pow2, advance_pow2, baseclass, extvalclass, kdd >::may_tock = stypebits < tick_limit_pow2 static constexpr private
Definition at line 1168 of file pcg_random.hpp.
rtypebits
template<bitcount_t table_pow2, bitcount_t advance_pow2, typename baseclass , typename extvalclass , bool kdd = true> constexpr bitcount_t pcg_detail::extended< table_pow2, advance_pow2, baseclass, extvalclass, kdd >::rtypebits = sizeof(result_type)*8 static constexpr private
Definition at line 1149 of file pcg_random.hpp.
stypebits
template<bitcount_t table_pow2, bitcount_t advance_pow2, typename baseclass , typename extvalclass , bool kdd = true> constexpr bitcount_t pcg_detail::extended< table_pow2, advance_pow2, baseclass, extvalclass, kdd >::stypebits = sizeof(state_type)*8 static constexpr private
Definition at line 1150 of file pcg_random.hpp.
table_mask
template<bitcount_t table_pow2, bitcount_t advance_pow2, typename baseclass , typename extvalclass , bool kdd = true> constexpr state_type pcg_detail::extended< table_pow2, advance_pow2, baseclass, extvalclass, kdd >::table_mask static constexpr private
Initial value:
=
        (state_type(1U) << table_pow2) - state_type(1U)
Definition at line 1156 of file pcg_random.hpp.
table_shift
template<bitcount_t table_pow2, bitcount_t advance_pow2, typename baseclass , typename extvalclass , bool kdd = true> constexpr size_t pcg_detail::extended< table_pow2, advance_pow2, baseclass, extvalclass, kdd >::table_shift = stypebits - table_pow2 static constexpr private
Definition at line 1155 of file pcg_random.hpp.
table_size
template<bitcount_t table_pow2, bitcount_t advance_pow2, typename baseclass , typename extvalclass , bool kdd = true> constexpr size_t pcg_detail::extended< table_pow2, advance_pow2, baseclass, extvalclass, kdd >::table_size = 1UL << table_pow2 static constexpr private
Definition at line 1154 of file pcg_random.hpp.
tick_limit_pow2
template<bitcount_t table_pow2, bitcount_t advance_pow2, typename baseclass , typename extvalclass , bool kdd = true> constexpr bitcount_t pcg_detail::extended< table_pow2, advance_pow2, baseclass, extvalclass, kdd >::tick_limit_pow2 = 64U static constexpr private
Definition at line 1152 of file pcg_random.hpp.
tick_mask
template<bitcount_t table_pow2, bitcount_t advance_pow2, typename baseclass , typename extvalclass , bool kdd = true> constexpr state_type pcg_detail::extended< table_pow2, advance_pow2, baseclass, extvalclass, kdd >::tick_mask static constexpr private
Initial value:
=
        may_tick ? state_type(
                       (uint64_t(1) << (advance_pow2*may_tick)) - 1)
                 : ~state_type(0U)
Definition at line 1162 of file pcg_random.hpp.
tick_shift
template<bitcount_t table_pow2, bitcount_t advance_pow2, typename baseclass , typename extvalclass , bool kdd = true> constexpr size_t pcg_detail::extended< table_pow2, advance_pow2, baseclass, extvalclass, kdd >::tick_shift = stypebits - advance_pow2 static constexpr private
Definition at line 1161 of file pcg_random.hpp.
The documentation for this class was generated from the following file:
pcg_random.hpp