Project GAIM: crossover.cpp File Reference
crossover.cpp File Reference
Functions
std::vector< REAL_ > one_point_crossover (std::vector< REAL_ > parent1, std::vector< REAL_ > parent2)
Applies a crossover operator on the genomes of two parents (parent1 and parent2) to create a child genome.
std::vector< REAL_ > two_point_crossover (std::vector< REAL_ > parent1, std::vector< REAL_ > parent2)
Two-point crossover operator.
std::vector< REAL_ > uniform_crossover (std::vector< REAL_ > parent1, std::vector< REAL_ > parent2)
Uniform crossover operator.
std::vector< REAL_ > flat_crossover (std::vector< REAL_ > parent1, std::vector< REAL_ > parent2)
Flat crossover operator.
std::vector< REAL_ > discrete_crossover (std::vector< REAL_ > parent1, std::vector< REAL_ > parent2)
Discrete crossover operator.
std::vector< REAL_ > order_one_crossover (std::vector< REAL_ > parent1, std::vector< REAL_ > parent2)
Order-one crossover operator.
Detailed Description
Implements extra crossover operators, which specify how genes from two parent genomes will be combined to produce a child genome. Where applicable, one of two possible children will result with equal probability.
The methods exit fatally if the size of genomes of the two parents is unequal.
Definition in file crossover.cpp.
Function Documentation
discrete_crossover()
std::vector<REAL_> discrete_crossover (std::vector< REAL_ > parent1, std::vector< REAL_ > parent2)
Discrete crossover operator.
Performs a discrete crossover operation. Genes from both parent are combined in a random way, slightly different from uniform crossover. The second parent's genes replace genes from the first parent's genome in a random way. For each gene a random number {0, 1} is drawn and defines the replacement. In the case of a 0 being drawn, the second parent's gene replaces the first parent's gene.
Parameters
[in] parent1 First parent's genome
[in] parent2 Second parent's genome
Returns
Offspring's genome
Definition at line 207 of file crossover.cpp.
Referenced by PYBIND11_MODULE().
flat_crossover()
std::vector<REAL_> flat_crossover (std::vector< REAL_ > parent1, std::vector< REAL_ > parent2)
Flat crossover operator.
Performs a "flat" crossover operation. Genes from both parent are combined in as by linear mixing, similar to alpha blending. A random variate is chosen to specify
the mixing weight.
Parameters
[in] parent1 First parent's genome
[in] parent2 Second parent's genome
Returns
Offspring's genome
Definition at line 171 of file crossover.cpp.
Referenced by PYBIND11_MODULE().
one_point_crossover()
std::vector<REAL_> one_point_crossover (std::vector< REAL_ > parent1, std::vector< REAL_ > parent2)
Applies a crossover operator on the genomes of two parents (parent1 and parent2) to create a child genome.
Extra Crossover functions.
By default, this is a one-point crossover operator.
Parameters
[in] parent1 Genome of the first parent
[in] parent2 Genome of the second parent
Returns
The genome of a child as a vector of type REAL_
Definition at line 41 of file crossover.cpp.
Referenced by GA::crossover(), and PYBIND11_MODULE().
order_one_crossover()
std::vector<REAL_> order_one_crossover (std::vector< REAL_ > parent1, std::vector< REAL_ > parent2)
Order-one crossover operator.
Performs an order-one crossover operation. It starts from the half genome of the first parent and as long as the genes between the two parents are different, it copies parent 2's genes to the child's genome.
Note
This operator is useful in problems involving permuations. The rule is somewhat different from traditional single-point crossover, which has no guarantees of preserving parent A's half genome.
Parameters
[in] parent1 First parent's genome
[in] parent2 Second parent's genome
Returns
Offspring's genome
Definition at line 247 of file crossover.cpp.
Referenced by PYBIND11_MODULE().
two_point_crossover()
std::vector<REAL_> two_point_crossover (std::vector< REAL_ > parent1, std::vector< REAL_ > parent2)
Two-point crossover operator.
Performs a two-point crossover. Two random points on the genome are drawn from a uniform distribution and the genes within the
area defined by the two points is swapped between parents.
Parameters
[in] parent1 First parent's genome
[in] parent2 Second parent's genome
Returns
Offspring's genome
Definition at line 82 of file crossover.cpp.
Referenced by PYBIND11_MODULE().
uniform_crossover()
std::vector<REAL_> uniform_crossover (std::vector< REAL_ > parent1, std::vector< REAL_ > parent2)
Uniform crossover operator.
Performs a uniform crossover operation. Each gene is chosen from one parent or the other with equal probability.
Parameters
[in] parent1 First parent's genome
[in] parent2 Second parent's genome
Returns
Offspring's genome
Definition at line 130 of file crossover.cpp.
Referenced by PYBIND11_MODULE().