Project GAIM: gaim.h File Reference
gaim.h File Reference
Classes
struct parameter_sel
Structure containing initialization parameters for the selection operator.
struct parameter_cross
Structure containing initialization parameters for the crossover operator.
struct parameter_mut
Structure containing initialization parameters for mutation operator.
struct parameter_ga
Structure containing initialization parameters for GA-based optimization.
struct parameter_im
Structure containing initialization parameters for an Island Model.
struct parameter_pr
Structure containing display parameters controlling which information is printed.
struct individual
Structure representing an individual.
struct ga_results
Structure that holds the returned results from the ga_optimization function.
class GA
Genetic Algorithm main class.
class IM
Island Model main class.
Typedefs
typedef struct parameter_sel sel_parameter_s
Structure containing initialization parameters for the selection operator.
typedef struct parameter_cross cross_parameter_s
Structure containing initialization parameters for the crossover operator.
typedef struct parameter_mut mut_parameter_s
Structure containing initialization parameters for mutation operator.
typedef struct parameter_ga ga_parameter_s
Structure containing initialization parameters for GA-based optimization.
typedef struct parameter_im im_parameter_s
Structure containing initialization parameters for an Island Model.
typedef struct parameter_pr pr_parameter_s
Structure containing display parameters controlling which information is printed.
typedef struct individual individual_s
Structure representing an individual.
typedef struct ga_results ga_results_s
Structure that holds the returned results from the ga_optimization function.
Functions
ga_results_s run_islands (REAL_(*func)(REAL_ *, size_t), im_parameter_s, ga_parameter_s, pr_parameter_s, std::string)
It runs an island model using pthreads.
void remove_at (std::vector< size_t > &, typename std::vector< size_t >::size_type)
Removes an element from a vector by swaping the element at position n with the last one and poping it out of the vector.
size_t int_random (size_t, size_t)
Integer uniform distribution.
REAL_ float_random (REAL_, REAL_)
Float uniform distribution.
bool compare_fitness (const individual_s, const individual_s)
Auxiliary Functions declarations.
REAL_ average_fitness (REAL_, const individual_s)
This is a helper function serving as an binary operator for std:accumulate.
bool is_path_exist (const std::string &)
Checks if the given path (directory or file) exists.
int mkdir_ (const std::string &)
Attempts to make a directory.
int make_dir (const std::string &)
Attempts to make a directory.
int remove_file (const std::string)
Deletes a file.
REAL_ calculate_whitley_factor (REAL_)
Calculates the Whitley factor used in Whitley's selection method.
REAL_ maximum_fitness (std::vector< individual_s >)
A naive implementation of maximum.
REAL_ nonselected_maximum_fitness (std::vector< individual_s >)
Computes the maximum fitness of all the non-selected (from a selection operator) indivuduals of a population.
REAL_ cumulative_fitness (std::vector< individual_s >)
Computes the cumulative fitness of a population based on which individuals have not been yet selected.
REAL_ vector_norm (std::vector< REAL_ >)
Vector's Euclidean norm.
int argmin (std::vector< REAL_ >)
Argmin.
int argmax (std::vector< REAL_ >)
Argmax.
std::vector< REAL_ > compute_population_norms (std::vector< GA >)
Compute population norms.
ga_results return_best_results (std::vector< GA >, std::string)
Return best results.
ga_results_s independent_runs (REAL_(*func)(REAL_ *, size_t), ga_parameter_s *, pr_parameter_s *, std::string)
Multithread and Islands functions declarations.
std::string center (const std::string, const int)
Printing Functions.
std::string prd (const double, const int, const int)
void print_fitness (std::vector< individual_s > &, size_t unique_id=0, std::string write_to="stdout")
void print_bsf (std::vector< REAL_ >, size_t unique_id=0, std::string write_to="stdout")
void print_avg_fitness (std::vector< REAL_ >, size_t unique_id=0, std::string write_to="stdout")
void print_best_genome (std::vector< REAL_ >, size_t unique_id=0, std::string write_to="stdout")
void print_results (std::vector< individual_s >, std::vector< REAL_ >, std::vector< REAL_ >, std::vector< REAL_ >, size_t, pr_parameter_s *)
REAL_ sphere (REAL_ *, size_t)
Demo objective/fitness functions End-user can define more at her/his will.
REAL_ rastrigin (std::vector< REAL_ > &)
REAL_ schwefel (std::vector< REAL_ > &)
REAL_ griewank (std::vector< REAL_ > &)
REAL_ tsm (std::vector< REAL_ > &x)
std::tuple< ga_parameter_s, pr_parameter_s, im_parameter_s > read_parameters_file (const char *)
Parameters files.
void print_parameters (ga_parameter_s, pr_parameter_s, im_parameter_s)
Prints parameters to a .dat file, or to stdout if "stdout" is specified.
ga_results_s ga_optimization (REAL_(*func)(REAL_ *, size_t), size_t n_generations, size_t population_size, size_t genome_size, size_t n_offsprings, size_t n_replacements, size_t n_rounds, std::vector< REAL_ > a, std::vector< REAL_ > b, std::string clipping="universal", std::string clipping_fname="clip_file.dat", std::string selection_method="ktournament", REAL_ bias=1.5, size_t num_parents=2, size_t lower_bound=1, size_t k=2, bool replace=false, std::string crossover_method="one_point", std::string mutation_method="delta", REAL_ mutation_rate=0.5, REAL_ mutation_var=0.5, REAL_ low_bound=0.0, REAL_ up_bound=1.0, size_t order=1, bool is_real=true, bool is_im_enabled=false, size_t n_islands=5, size_t n_immigrants=4, size_t migration_interval=500, std::string pickup_method="elite", std::string replace_method="poor", std::string im_graph_fname="star_graph.dat", std::string experiment_id="experiment-1", std::string log_path="./data/", std::string return_type="minimum", bool log_fitness=false, bool log_average_fitness=true, bool log_bsf=true, bool log_best_genome=true)
Interface functions (to use GAIM through other programming languages.
void ga_optimization_python (REAL_(*func)(REAL_ *, size_t), size_t n_generations, size_t population_size, size_t genome_size, size_t n_offsprings, size_t n_replacements, size_t n_rounds, REAL_ *a, REAL_ *b, char *clipping, char *clipping_fname, char *selection_method, REAL_ bias, size_t num_parents, size_t lower_bound, size_t k, bool replace, char *crossover_method, char *mutation_method, REAL_ mutation_rate, REAL_ mutation_var, REAL_ low_bound, REAL_ up_bound, size_t order, bool is_real, bool is_im_enabled, size_t n_islands, size_t n_immigrants, size_t migration_interval, char *pickup_method, char *replace_method, char *im_graph_fname, char *experiment_id, char *log_path, char *return_type, bool log_fitness, bool log_average_fitness, bool log_bsf, bool log_best_genome, REAL_ **genoe, REAL_ **bsf, REAL_ **agv_fitness)
Interface function for calling GAIM from within any other C/C++ source code of software (libgaim).
Detailed Description
Header file of GA and IM classes (and their methods), comprising the main external interface.
Definition in file gaim.h.
Typedef Documentation
cross_parameter_s
typedef struct parameter_cross cross_parameter_s
Structure containing initialization parameters for the crossover operator.
A structure that contains the parameters for specifying a crossover method.
ga_parameter_s
typedef struct parameter_ga ga_parameter_s
Structure containing initialization parameters for GA-based optimization.
A structure that contains all the parameters for specifying a Genetic Algorithms simulation, including how many generations it will run for, what the size of the population is, what the size of the genome is, what the endpoints of the interval to optimize on are, how many offspring are to be produced and how many individuals are to be replaced. It is typical in a Genetic Algorithm without elitism to replace the entire population. The number of indepedent runs can also be specified, if you are trying to derive an Monte Carlo estimate of fitness.
ga_results_s
typedef struct ga_results ga_results_s
Structure that holds the returned results from the ga_optimization function.
A structure that keeps all the results (best genome, BSF, and average fitness). This data structure is used only from the ga_optimization function.
im_parameter_s
typedef struct parameter_im im_parameter_s
Structure containing initialization parameters for an Island Model.
A structure that contains all the parameters for running an Island Model (IM), a GA with multiple subpopulations and structured migrations.
individual_s
typedef struct individual individual_s
Structure representing an individual.
A structure that represents an individual and carries all the necessary information about an individual, including ID, fitness, and genome.
mut_parameter_s
typedef struct parameter_mut mut_parameter_s
Structure containing initialization parameters for mutation operator.
A structure that contains all the parameters for specifying a mutation operator. This data structure includes the mutation method, the mutation rate and variance (delta mutation), the lower and upper bounds for the fusion and non-uniform mutation operators. Furthermore, it contains the time and order parameters for the nonuniform mutation operator and a parameter that defines if the genome is of type int or real (float or double).
pr_parameter_s
typedef struct parameter_pr pr_parameter_s
Structure containing display parameters controlling which information is printed.
A structure that contains all the parameters for printing information about the GA or the IM.
sel_parameter_s
typedef struct parameter_sel sel_parameter_s
Structure containing initialization parameters for the selection operator.
A structure that contains all the parameters for specifying a selection method and its corresponding parameters. It includes the selection method, the number of parents (individuals) that will be selected for reproduction, an integer k that defines the tournament size (how many individuals from the population will be drawn randomly), a replace parameter that determines if the individuals will be selected with replacement or not. Furthermore, it contains the lower bound (lowest index) from which the selection begins for the truncation method. Finally, includes the bias that controls how strongly the high rank individuals are favored when the Whithley selection method is used.
Function Documentation
argmax()
int argmax (std::vector< REAL_ > x)
Argmax.
It returns the index of the maximum element in a vector.
Parameters
[in] x A vector of type REAL_
Returns
An integer as the index of the maximum element in vector x
Definition at line 74 of file auxiliary_funs.cpp.
References distance().
Referenced by return_best_results().
argmin()
int argmin (std::vector< REAL_ > x)
Argmin.
It returns the index of the minimum element in a vector.
Parameters
[in] x A vector of type REAL_
Returns
An integer as the index of the minimum element in vector x
Definition at line 88 of file auxiliary_funs.cpp.
References distance().
Referenced by return_best_results().
average_fitness()
REAL_ average_fitness (REAL_ x, const individual_s y)
This is a helper function serving as an binary operator for std:accumulate.
It helps add up the fitness belonging to individuals so that the cumulative fitness in the population can be computed, which is necessary for roulette-wheel selection, etc.
See also
one_generation_step()
Parameters
[in] x REAL_, it is the current accumulated fitness.
[in] y Data struct of individual_s type, it provides the new fitness of an idividual.
Returns
The current accumulated fitness yielded in the accumulation (usually for the whole population.)
Definition at line 272 of file auxiliary_funs.cpp.
References individual::fitness.
Referenced by GA::roulette_wheel_selection(), and GA::run_one_generation().
calculate_whitley_factor()
REAL_ calculate_whitley_factor (REAL_ bias)
Calculates the Whitley factor used in Whitley's selection method.
Parameters
[in] bias Governs how strong one would like to favor high ranked individuals.
Returns
The factor bias - sqrt(bias^2 - 4 * (bias - 1) * rand(0, 1))/2/(bias-1)
Warning
Bias should be in (1, 2]
See also
whitley_selection()
Definition at line 443 of file selection.cpp.
References float_random().
Referenced by GA::whitley_selection().
center()
std::string center (const std::string s, const int w)
Printing Functions.
Printing Functions.
Parameters
[in] s The input string to be centered
[in] w The width of the total string
Returns
A string that is centered and padded with spaces
Definition at line 55 of file logging.cpp.
Referenced by print_avg_fitness(), print_bsf(), and print_fitness().
compare_fitness()
bool compare_fitness (const individual_s x, const individual_s y)
Auxiliary Functions declarations.
Auxiliary Functions declarations.
Parameters
[in] x Data struct of type const individual_s.
[in] y Data struct of type const individual_s.
Returns
True if x.fitness < y.fitness, false otherwise.
Definition at line 252 of file auxiliary_funs.cpp.
References individual::fitness.
Referenced by GA::linear_rank_selection(), GA::next_generation(), GA::sort_population(), and GA::truncation_selection().
compute_population_norms()
std::vector<REAL_> compute_population_norms (std::vector< GA > x)
Compute population norms.
It computes the Euclidean norms of all individual's genome within a population.
Parameters
[in] a A vector of type GA
Returns
A vector of REAL_ that contains the norms of all population's individuals
Definition at line 59 of file auxiliary_funs.cpp.
References vector_norm().
Referenced by return_best_results().
cumulative_fitness()
REAL_ cumulative_fitness (std::vector< individual_s > population)
Computes the cumulative fitness of a population based on which individuals have not been yet selected.
This function is used in the roulette_wheel_selection with replacement.
Parameters
[in] population A vector of the entire population.
Returns
The cumulative fitness of a population.
See also
roulette_wheel_selection()
Definition at line 184 of file auxiliary_funs.cpp.
Referenced by GA::roulette_wheel_selection().
float_random()
REAL_ float_random (REAL_ a, REAL_ b)
Float uniform distribution.
It returns a float random number in the interval [a, b] (uniform distribution).
Parameters
[in] a Lower limit of range [a, b] from which a random float will be drawn.
[in] b Upper limit of range [a, b].
Returns
A float number in [a, b].
Definition at line 151 of file auxiliary_funs.cpp.
Referenced by calculate_whitley_factor(), GA::roulette_wheel_selection(), and GA::stochastic_roulette_wheel_selection().
ga_optimization()
ga_results_s ga_optimization (REAL_(*)(REAL_ *, size_t) func, size_t n_generations, size_t population_size, size_t genome_size, size_t n_offsprings, size_t n_replacements, size_t n_rounds, std::vector< REAL_ > a, std::vector< REAL_ > b, std::string clipping, std::string clipping_fname, std::string selection_method, REAL_ bias, size_t num_parents, size_t lower_bound, size_t k, bool replace, std::string crossover_method, std::string mutation_method, REAL_ mutation_rate, REAL_ mutation_var, REAL_ low_bound, REAL_ up_bound, size_t order, bool is_real, bool is_im_enabled, size_t n_islands, size_t n_immigrants, size_t migration_interval, std::string pickup_method, std::string replace_method, std::string im_graph_fname, std::string experiment_id, std::string log_path, std::string return_type, bool log_fitness, bool log_average_fitness, bool log_bsf, bool log_best_genome)
Interface functions (to use GAIM through other programming languages.
Interface functions (to use GAIM through other programming languages.
It initializes all the necessary parameters and vectors for evolving a population of individuals based on a predetermined Genetic Algorithm (GA).
Parameters
[in] func A pointer function to the objective/fitness function
[in] n_generations Number of generations
[in] population_size Number of individuals within a population
[in] genome_size How many parameters the fitness function has
[in] n_offsprings Number of new candidate individuals (children)
[in] n_replacements Number of parents to be replaced per generation
[in] n_rounds Number of independent experiments to run
[in] a Vector with genes lower bounds
[in] b Vector with genes upper bounds
[in] clipping Gene's clipping method (universal: all the genes are clamped with the same values a and b. Individual: Each gene has its own clamped values a and b.
[in] clipping_fname Filename of clipping file
[in] selection_method Selection method must be one of the following: ktournament, truncation, linear_rank, random, roulette, stochastic_roulette, whitley
[in] bias This is the bias term when the Whitley selection method is used
[in] num_parents Determines how many parents will be selected from the population
[in] lower_bound Determines the starting index when the Truncation selection method is used
[in] k Determines the tournament size (number of individuals to choose) when the k-tournament method is used
[in] replace If it's true then any selection method will choose the parents from the original population with replacement. param[in] crossover_method Crossover method must be one of the following: one_point, two_point, uniform, flat, discrete, first_order
[in] mutation_method Mutation method muse be one of the following: delta, random, nonuniform, fusion, swap_mutation
[in] mutation_rate The mutation rate when the delta mutation method is used
[in] mutation_var The mutation variance when the delta mutation method is used
[in] low_bound Determines the lower bound for the uniform distributions used in all mutation methods
[in] up_bound Determines the upper bound for the uniform distributions used in all mutation methods
[in] order Defines the order of the Nonuniform delta mutation
[in] is_real Determines if the mutation operators will operate on real or integer numbers
[in] is_im_enabled Enables/disables the island model operation
[in] n_islands Number of islands in a Island Model
[in] n_immigrants Number of individuals to move from one island to another (only for island model)
[in] migration_interval Determines how frequent individuals have to move from one island to another
[in] pickup_method Selection method of migrating individuals in an island model, poor: Select individuals with lowest fitness, elite: select individuals with the highest fitness, and random: select individuals randomly
[in] replace_method Replacement method of individuals on islands who receive immigrants. Three method (poor, elite, and random).
[in] im_graph_fname The filename of the file that contains the connectivity graph for an island model.
[in] experiment_id A name for any optimization (experiment). GAIM will store all the parameters of the optimization in a file with that name
[in] log_path The directory in which all the results and logs will be saved
[in] return_type A string that determines which run the genome will be returned. The available options are: (*) "minimum" - the genome with the minimum Euclidean distance is returned (*) "maximum" - the genome with the maximum Euclidean distance is returned (*) "random" - a randomly chosen genome is returned
[in] log_fitness Enable/disable the track of individuals' fitness
[in] log_average_fitness Enable/disable the track of population (average) fitness
[in] log_bsf Enable/disable the track of Best So far Fitness (BSF) fitness.
[in] log_best_genome Enable/disable the track of the best genome
Returns
res A ga_results_s data structure that contains the average fitness, the BSF, and the best genome found from the GA.
Definition at line 109 of file interface.cpp.
References parameter_ga::a, parameter_im::adj_list_fname, ga_results::average_fitness, parameter_ga::b, parameter_sel::bias, ga_results::bsf, parameter_ga::clipping, parameter_ga::clipping_fname, parameter_ga::cross_pms, parameter_cross::crossover_method, GA::evolve(), parameter_pr::experiment_name, GA::fitness, parameter_ga::generations, ga_results::genome, parameter_ga::genome_size, GA::get_average_fitness(), GA::get_best_genome(), GA::get_bsf(), independent_runs(), parameter_im::is_im_enabled, parameter_mut::is_real, parameter_sel::k, parameter_mut::low_bound, parameter_sel::lower_bound, make_dir(), parameter_im::migration_interval, parameter_ga::mut_pms, parameter_mut::mutation_method, parameter_mut::mutation_rate, parameter_im::num_immigrants, parameter_im::num_islands, parameter_ga::num_offsprings, parameter_sel::num_parents, parameter_ga::num_replacement, parameter_mut::order, parameter_im::pick_method, parameter_ga::population_size, parameter_pr::print_average_fitness, parameter_pr::print_best_genome, parameter_pr::print_bsf, parameter_pr::print_fitness, print_parameters(), parameter_sel::replace, parameter_im::replace_method, run_islands(), parameter_ga::runs, parameter_ga::sel_pms, parameter_sel::selection_method, parameter_mut::up_bound, parameter_mut::variance, and parameter_pr::where2write.
ga_optimization_python()
void ga_optimization_python (REAL_(*)(REAL_ *, size_t) func, size_t n_generations, size_t population_size, size_t genome_size, size_t n_offsprings, size_t n_replacements, size_t n_rounds, REAL_ * a, REAL_ * b, char * clipping, char * clipping_fname, char * selection_method, REAL_ bias, size_t num_parents, size_t lower_bound, size_t k, bool replace, char * crossover_method, char * mutation_method, REAL_ mutation_rate, REAL_ mutation_var, REAL_ low_bound, REAL_ up_bound, size_t order, bool is_real, bool is_im_enabled, size_t n_islands, size_t n_immigrants, size_t migration_interval, char * pickup_method, char * replace_method, char * im_graph_fname, char * experiment_id, char * log_path, char * return_type, bool log_fitness, bool log_average_fitness, bool log_bsf, bool log_best_genome, REAL_ ** genome, REAL_ ** bsf, REAL_ ** avg_fitness)
Interface function for calling GAIM from within any other C/C++ source code of software (libgaim).
It initializes all the necessary parameters and vectors for evolving a population of individuals based on a predetermined Genetic Algorithm (GA).
See ga_optimization for more details on the arguments.
Definition at line 249 of file interface.cpp.
References parameter_ga::a, parameter_im::adj_list_fname, ga_results::average_fitness, parameter_ga::b, parameter_sel::bias, ga_results::bsf, parameter_ga::clipping, parameter_ga::clipping_fname, parameter_ga::cross_pms, parameter_cross::crossover_method, GA::evolve(), parameter_pr::experiment_name, GA::fitness, parameter_ga::generations, ga_results::genome, parameter_ga::genome_size, GA::get_average_fitness(), GA::get_best_genome(), GA::get_bsf(), independent_runs(), parameter_im::is_im_enabled, parameter_mut::is_real, parameter_sel::k, parameter_mut::low_bound, parameter_sel::lower_bound, make_dir(), parameter_im::migration_interval, parameter_ga::mut_pms, parameter_mut::mutation_method, parameter_mut::mutation_rate, parameter_im::num_immigrants, parameter_im::num_islands, parameter_ga::num_offsprings, parameter_sel::num_parents, parameter_ga::num_replacement, parameter_mut::order, parameter_im::pick_method, parameter_ga::population_size, parameter_pr::print_average_fitness, parameter_pr::print_best_genome, parameter_pr::print_bsf, parameter_pr::print_fitness, print_parameters(), parameter_sel::replace, parameter_im::replace_method, run_islands(), parameter_ga::runs, parameter_ga::sel_pms, parameter_sel::selection_method, parameter_mut::up_bound, parameter_mut::variance, and parameter_pr::where2write.
griewank()
REAL_ griewank (std::vector< REAL_ > &)
independent_runs()
ga_results_s independent_runs (REAL_(*)(REAL_ *, size_t) func, ga_parameter_s * ga_pms, pr_parameter_s * pr_pms, std::string return_type)
Multithread and Islands functions declarations.
Multithread and Islands functions declarations.
Runs an X number of GAs in parallel and independently using threads.
Parameters
[in] func A pointer to the fitness function
[in] ga_pms Structure of GA parameters
[in] pr_pms Structure of printing parameters
[in] return_type A string that determines which run the genome will be returned. The available options are: (*) "minimum" - the genome with the minimum Euclidean distance is returned (*) "maximum" - the genome with the maximum Euclidean distance is returned (*) "random" - a randomly chosen genome is returned
Returns
A data structure of type ga_results_s with the selected genome.
Create the data directory if it doesn't exist
Set the fitness function for every run
Instantiate threads and GAs
Join threads
Choose from all the runs which genome to return
Definition at line 45 of file parallel_ga.cpp.
References GA::evolve(), parameter_ga::generations, make_dir(), return_best_results(), parameter_ga::runs, and parameter_pr::where2write.
Referenced by ga_optimization(), and ga_optimization_python().
int_random()
size_t int_random (size_t a, size_t b)
Integer uniform distribution.
It returns an integer random number in the interval [a, b] (uniform distribution).
Parameters
[in] a Lower limit of range [a, b] from which a random integer will be drawn.
[in] b Upper limit of range [a, b].
Returns
An integer number in [a, b].
Definition at line 134 of file auxiliary_funs.cpp.
Referenced by GA::random_selection(), return_best_results(), GA::stochastic_roulette_wheel_selection(), and GA::truncation_selection().
is_path_exist()
bool is_path_exist (const std::string & str)
Checks if the given path (directory or file) exists.
Parameters
str const string that contains the name of the path.
Returns
True if the path exists and false otherwise.
Definition at line 284 of file auxiliary_funs.cpp.
Referenced by make_dir(), print_avg_fitness(), print_best_genome(), print_bsf(), and print_fitness().
make_dir()
int make_dir (const std::string & path)
Attempts to make a directory.
Parameters
[in] path const string that contains the name (path) of the new directory.
Returns
Zero upon successfully created directory, one otherwise.
Definition at line 332 of file auxiliary_funs.cpp.
References is_path_exist(), and mkdir_().
Referenced by ga_optimization(), ga_optimization_python(), independent_runs(), read_parameters_file(), and run_islands().
maximum_fitness()
REAL_ maximum_fitness (std::vector< individual_s > population)
A naive implementation of maximum.
This function finds the maximum fitness and returns it.
Parameters
[in] population A vector of the entire population.
Returns
The maximum fitness of a population.
Definition at line 203 of file auxiliary_funs.cpp.
Referenced by GA::stochastic_roulette_wheel_selection().
mkdir_()
int mkdir_ (const std::string & path)
Attempts to make a directory.
Parameters
[in] path const string that contains the name (path) of the new directory.
Returns
Zero upon successfully created directory, one otherwise.
Definition at line 312 of file auxiliary_funs.cpp.
Referenced by make_dir().
nonselected_maximum_fitness()
REAL_ nonselected_maximum_fitness (std::vector< individual_s > population)
Computes the maximum fitness of all the non-selected (from a selection operator) indivuduals of a population.
Note
This functions is meant to be used with selection methods that use the maximum fitness of a population and have the selection-with-replacement option disabled.
Parameters
[in] population A vector of the entire population.
Returns
The maximum fitness of a population (of the non-selected individuals).
Definition at line 229 of file auxiliary_funs.cpp.
Referenced by GA::stochastic_roulette_wheel_selection().
prd()
std::string prd (const double , const int , const int)
print_avg_fitness()
void print_avg_fitness (std::vector< REAL_ > , size_t unique_id = 0, std::string write_to = "stdout")
print_best_genome()
void print_best_genome (std::vector< REAL_ > , size_t unique_id = 0, std::string write_to = "stdout")
print_bsf()
void print_bsf (std::vector< REAL_ > , size_t unique_id = 0, std::string write_to = "stdout")
print_fitness()
void print_fitness (std::vector< individual_s > & , size_t unique_id = 0, std::string write_to = "stdout")
print_parameters()
void print_parameters (ga_parameter_s ga_pms, pr_parameter_s pr_pms, im_parameter_s im_pms)
Prints parameters to a .dat file, or to stdout if "stdout" is specified.
Prints all the parameters to the standard output (if "stdout" is specified as where2write in the printing params) and to a file for debugging purposes.
Parameters
[in] ga_pms Structure of GA parameters
[in] pr_pms Structure of printing parameters
[in] im_pms Structure of IM parameters
Returns
Nothing (void function)
Definition at line 262 of file parameters.cpp.
References parameter_sel::bias, parameter_ga::clipping, parameter_ga::clipping_fname, parameter_ga::cross_pms, parameter_cross::crossover_method, parameter_pr::experiment_name, parameter_ga::generations, parameter_ga::genome_size, parameter_im::is_im_enabled, parameter_mut::is_real, parameter_sel::k, parameter_mut::low_bound, parameter_sel::lower_bound, parameter_im::migration_interval, parameter_ga::mut_pms, parameter_mut::mutation_method, parameter_mut::mutation_rate, parameter_im::num_immigrants, parameter_im::num_islands, parameter_ga::num_offsprings, parameter_sel::num_parents, parameter_ga::num_replacement, parameter_mut::order, parameter_im::pick_method, parameter_ga::population_size, parameter_pr::print_average_fitness, parameter_pr::print_best_genome, parameter_pr::print_bsf, parameter_pr::print_fitness, parameter_sel::replace, parameter_im::replace_method, parameter_ga::runs, parameter_ga::sel_pms, parameter_sel::selection_method, parameter_mut::up_bound, parameter_mut::variance, and parameter_pr::where2write.
Referenced by ga_optimization(), and ga_optimization_python().
print_results()
void print_results (std::vector< individual_s > , std::vector< REAL_ > , std::vector< REAL_ > , std::vector< REAL_ > , size_t , pr_parameter_s *)
rastrigin()
REAL_ rastrigin (std::vector< REAL_ > &)
read_parameters_file()
std::tuple<ga_parameter_s, pr_parameter_s, im_parameter_s> read_parameters_file (const char * fname)
Parameters files.
Parameters files.
Reads a configuration file (.cfg) of libconfig format, parses it and loads the parameters into the internal data structures.
Parameters
[in] fname Configuration filename (libconfig format).
Returns
A tuple of three structures (parameter_s, print_params_s, im_parameter_s) -> (GA, printing, IM).
Definition at line 44 of file parameters.cpp.
References parameter_ga::a, parameter_im::adj_list_fname, parameter_ga::b, parameter_sel::bias, parameter_ga::clipping, parameter_ga::clipping_fname, parameter_ga::cross_pms, parameter_cross::crossover_method, parameter_pr::experiment_name, parameter_ga::generations, parameter_ga::genome_size, parameter_im::is_im_enabled, parameter_mut::is_real, parameter_sel::k, parameter_mut::low_bound, parameter_sel::lower_bound, make_dir(), parameter_im::migration_interval, parameter_ga::mut_pms, parameter_mut::mutation_method, parameter_mut::mutation_rate, parameter_im::num_immigrants, parameter_im::num_islands, parameter_ga::num_offsprings, parameter_sel::num_parents, parameter_ga::num_replacement, parameter_mut::order, parameter_im::pick_method, parameter_ga::population_size, parameter_pr::print_average_fitness, print_avg_fitness(), parameter_pr::print_best_genome, print_best_genome(), print_bsf(), parameter_pr::print_bsf, print_fitness(), parameter_pr::print_fitness, parameter_sel::replace, parameter_im::replace_method, parameter_ga::runs, parameter_ga::sel_pms, parameter_sel::selection_method, parameter_mut::up_bound, parameter_mut::variance, and parameter_pr::where2write.
remove_at()
void remove_at (std::vector< size_t > & v, std::vector< size_t >::size_type n)
Removes an element from a vector by swaping the element at position n with the last one and poping it out of the vector.
Parameters
[in] v The input vector from whith an element will be deleted.
[in] n The size_type of the vector (position of deleted element).
Returns
(void)
Definition at line 167 of file auxiliary_funs.cpp.
Referenced by GA::ktournament_selection(), and GA::stochastic_roulette_wheel_selection().
remove_file()
int remove_file (const std::string fname)
Deletes a file.
Parameters
[in] fname const string that contains the name of the file to being deleted.
Returns
Zero in the case of successful deletion, non-zero value otherwise.
Definition at line 298 of file auxiliary_funs.cpp.
return_best_results()
ga_results return_best_results (std::vector< GA > population, std::string return_type)
Return best results.
It computes the best genome based on the Euclidean norm.
Parameters
[in] x A vector of type REAL_
Returns
A data structure of type ga_results_s
Definition at line 103 of file auxiliary_funs.cpp.
References argmax(), argmin(), ga_results::average_fitness, ga_results::bsf, compute_population_norms(), ga_results::genome, and int_random().
Referenced by independent_runs(), and run_islands().
run_islands()
ga_results_s run_islands (REAL_(*)(REAL_ *, size_t) func, im_parameter_s im_pms, ga_parameter_s ga_pms, pr_parameter_s pr_pms, std::string return_type)
It runs an island model using pthreads.
Runs an X number of islands in parallel using threads.
Parameters
[in] func A pointer to the fitness function
[in] im_pms Structure of IM parameters
[in] ga_pms Structure of GA parameters
[in] pr_pms Structure of printing parameters
[in] return_type A string that determines which run the genome will be returned. The available options are: (*) "minimum" - the genome with the minimum Euclidean distance is returned (*) "maximum" - the genome with the maximum Euclidean distance is returned (*) "random" - a randomly chosen genome is returned
Returns
A data structure of type ga_results_s with the selected genome.
Create the data directory if it doesn't exist
Set the fitness function for every island
Evolve a GA on each island
Choose from all the islands which genome to return
Definition at line 381 of file island_ga.cpp.
References IM::evolve_islands(), IM::island, make_dir(), parameter_im::num_islands, return_best_results(), and parameter_pr::where2write.
Referenced by ga_optimization(), and ga_optimization_python().
schwefel()
REAL_ schwefel (std::vector< REAL_ > &)
sphere()
REAL_ sphere (REAL_ * x, size_t len)
Demo objective/fitness functions End-user can define more at her/his will.
Demo objective/fitness functions End-user can define more at her/his will.
Sphere cost function
Parameters
[in] x Vector
Returns
A number indicating the cost
Definition at line 39 of file test_functions.cpp.
Referenced by GA::GA().
tsm()
REAL_ tsm (std::vector< REAL_ > & x)
vector_norm()
REAL_ vector_norm (std::vector< REAL_ > x)
Vector's Euclidean norm.
It computes the Euclidean norm of a vector of type REAL_.
Parameters
[in] x A vector of type REAL_
Returns
The norm of x as type REAL_
Definition at line 41 of file auxiliary_funs.cpp.
Referenced by compute_population_norms().