Project GAIM: interface.cpp File Reference
interface.cpp File Reference
Functions
ga_results_s ga_optimization (REAL_(*func)(REAL_ *, size_t), size_t n_generations, size_t population_size, size_t genome_size, size_t n_offsprings, size_t n_replacements, size_t n_rounds, std::vector< REAL_ > a, std::vector< REAL_ > b, std::string clipping, std::string clipping_fname, std::string selection_method, REAL_ bias, size_t num_parents, size_t lower_bound, size_t k, bool replace, std::string crossover_method, std::string mutation_method, REAL_ mutation_rate, REAL_ mutation_var, REAL_ low_bound, REAL_ up_bound, size_t order, bool is_real, bool is_im_enabled, size_t n_islands, size_t n_immigrants, size_t migration_interval, std::string pickup_method, std::string replace_method, std::string im_graph_fname, std::string experiment_id, std::string log_path, std::string return_type, bool log_fitness, bool log_average_fitness, bool log_bsf, bool log_best_genome)
Interface function for calling GAIM from within any other C/C++ source code of software (libgaim).
void ga_optimization_python (REAL_(*func)(REAL_ *, size_t), size_t n_generations, size_t population_size, size_t genome_size, size_t n_offsprings, size_t n_replacements, size_t n_rounds, REAL_ *a, REAL_ *b, char *clipping, char *clipping_fname, char *selection_method, REAL_ bias, size_t num_parents, size_t lower_bound, size_t k, bool replace, char *crossover_method, char *mutation_method, REAL_ mutation_rate, REAL_ mutation_var, REAL_ low_bound, REAL_ up_bound, size_t order, bool is_real, bool is_im_enabled, size_t n_islands, size_t n_immigrants, size_t migration_interval, char *pickup_method, char *replace_method, char *im_graph_fname, char *experiment_id, char *log_path, char *return_type, bool log_fitness, bool log_average_fitness, bool log_bsf, bool log_best_genome, REAL_ **genome, REAL_ **bsf, REAL_ **avg_fitness)
Interface function for calling GAIM from within any other C/C++ source code of software (libgaim).
Detailed Description
Defines an interface function for calling game in a single-line code from within any other software.
Definition in file interface.cpp.
Function Documentation
ga_optimization()
ga_results_s ga_optimization (REAL_(*)(REAL_ *, size_t) func, size_t n_generations, size_t population_size, size_t genome_size, size_t n_offsprings, size_t n_replacements, size_t n_rounds, std::vector< REAL_ > a, std::vector< REAL_ > b, std::string clipping, std::string clipping_fname, std::string selection_method, REAL_ bias, size_t num_parents, size_t lower_bound, size_t k, bool replace, std::string crossover_method, std::string mutation_method, REAL_ mutation_rate, REAL_ mutation_var, REAL_ low_bound, REAL_ up_bound, size_t order, bool is_real, bool is_im_enabled, size_t n_islands, size_t n_immigrants, size_t migration_interval, std::string pickup_method, std::string replace_method, std::string im_graph_fname, std::string experiment_id, std::string log_path, std::string return_type, bool log_fitness, bool log_average_fitness, bool log_bsf, bool log_best_genome)
Interface function for calling GAIM from within any other C/C++ source code of software (libgaim).
Interface functions (to use GAIM through other programming languages.
It initializes all the necessary parameters and vectors for evolving a population of individuals based on a predetermined Genetic Algorithm (GA).
Parameters
[in] func A pointer function to the objective/fitness function
[in] n_generations Number of generations
[in] population_size Number of individuals within a population
[in] genome_size How many parameters the fitness function has
[in] n_offsprings Number of new candidate individuals (children)
[in] n_replacements Number of parents to be replaced per generation
[in] n_rounds Number of independent experiments to run
[in] a Vector with genes lower bounds
[in] b Vector with genes upper bounds
[in] clipping Gene's clipping method (universal: all the genes are clamped with the same values a and b. Individual: Each gene has its own clamped values a and b.
[in] clipping_fname Filename of clipping file
[in] selection_method Selection method must be one of the following: ktournament, truncation, linear_rank, random, roulette, stochastic_roulette, whitley
[in] bias This is the bias term when the Whitley selection method is used
[in] num_parents Determines how many parents will be selected from the population
[in] lower_bound Determines the starting index when the Truncation selection method is used
[in] k Determines the tournament size (number of individuals to choose) when the k-tournament method is used
[in] replace If it's true then any selection method will choose the parents from the original population with replacement. param[in] crossover_method Crossover method must be one of the following: one_point, two_point, uniform, flat, discrete, first_order
[in] mutation_method Mutation method muse be one of the following: delta, random, nonuniform, fusion, swap_mutation
[in] mutation_rate The mutation rate when the delta mutation method is used
[in] mutation_var The mutation variance when the delta mutation method is used
[in] low_bound Determines the lower bound for the uniform distributions used in all mutation methods
[in] up_bound Determines the upper bound for the uniform distributions used in all mutation methods
[in] order Defines the order of the Nonuniform delta mutation
[in] is_real Determines if the mutation operators will operate on real or integer numbers
[in] is_im_enabled Enables/disables the island model operation
[in] n_islands Number of islands in a Island Model
[in] n_immigrants Number of individuals to move from one island to another (only for island model)
[in] migration_interval Determines how frequent individuals have to move from one island to another
[in] pickup_method Selection method of migrating individuals in an island model, poor: Select individuals with lowest fitness, elite: select individuals with the highest fitness, and random: select individuals randomly
[in] replace_method Replacement method of individuals on islands who receive immigrants. Three method (poor, elite, and random).
[in] im_graph_fname The filename of the file that contains the connectivity graph for an island model.
[in] experiment_id A name for any optimization (experiment). GAIM will store all the parameters of the optimization in a file with that name
[in] log_path The directory in which all the results and logs will be saved
[in] return_type A string that determines which run the genome will be returned. The available options are: (*) "minimum" - the genome with the minimum Euclidean distance is returned (*) "maximum" - the genome with the maximum Euclidean distance is returned (*) "random" - a randomly chosen genome is returned
[in] log_fitness Enable/disable the track of individuals' fitness
[in] log_average_fitness Enable/disable the track of population (average) fitness
[in] log_bsf Enable/disable the track of Best So far Fitness (BSF) fitness.
[in] log_best_genome Enable/disable the track of the best genome
Returns
res A ga_results_s data structure that contains the average fitness, the BSF, and the best genome found from the GA.
Definition at line 109 of file interface.cpp.
References parameter_ga::a, parameter_im::adj_list_fname, ga_results::average_fitness, parameter_ga::b, parameter_sel::bias, ga_results::bsf, parameter_ga::clipping, parameter_ga::clipping_fname, parameter_ga::cross_pms, parameter_cross::crossover_method, GA::evolve(), parameter_pr::experiment_name, GA::fitness, parameter_ga::generations, ga_results::genome, parameter_ga::genome_size, GA::get_average_fitness(), GA::get_best_genome(), GA::get_bsf(), independent_runs(), parameter_im::is_im_enabled, parameter_mut::is_real, parameter_sel::k, parameter_mut::low_bound, parameter_sel::lower_bound, make_dir(), parameter_im::migration_interval, parameter_ga::mut_pms, parameter_mut::mutation_method, parameter_mut::mutation_rate, parameter_im::num_immigrants, parameter_im::num_islands, parameter_ga::num_offsprings, parameter_sel::num_parents, parameter_ga::num_replacement, parameter_mut::order, parameter_im::pick_method, parameter_ga::population_size, parameter_pr::print_average_fitness, parameter_pr::print_best_genome, parameter_pr::print_bsf, parameter_pr::print_fitness, print_parameters(), parameter_sel::replace, parameter_im::replace_method, run_islands(), parameter_ga::runs, parameter_ga::sel_pms, parameter_sel::selection_method, parameter_mut::up_bound, parameter_mut::variance, and parameter_pr::where2write.
ga_optimization_python()
void ga_optimization_python (REAL_(*)(REAL_ *, size_t) func, size_t n_generations, size_t population_size, size_t genome_size, size_t n_offsprings, size_t n_replacements, size_t n_rounds, REAL_ * a, REAL_ * b, char * clipping, char * clipping_fname, char * selection_method, REAL_ bias, size_t num_parents, size_t lower_bound, size_t k, bool replace, char * crossover_method, char * mutation_method, REAL_ mutation_rate, REAL_ mutation_var, REAL_ low_bound, REAL_ up_bound, size_t order, bool is_real, bool is_im_enabled, size_t n_islands, size_t n_immigrants, size_t migration_interval, char * pickup_method, char * replace_method, char * im_graph_fname, char * experiment_id, char * log_path, char * return_type, bool log_fitness, bool log_average_fitness, bool log_bsf, bool log_best_genome, REAL_ ** genome, REAL_ ** bsf, REAL_ ** avg_fitness)
Interface function for calling GAIM from within any other C/C++ source code of software (libgaim).
It initializes all the necessary parameters and vectors for evolving a population of individuals based on a predetermined Genetic Algorithm (GA).
See ga_optimization for more details on the arguments.
Definition at line 249 of file interface.cpp.
References parameter_ga::a, parameter_im::adj_list_fname, ga_results::average_fitness, parameter_ga::b, parameter_sel::bias, ga_results::bsf, parameter_ga::clipping, parameter_ga::clipping_fname, parameter_ga::cross_pms, parameter_cross::crossover_method, GA::evolve(), parameter_pr::experiment_name, GA::fitness, parameter_ga::generations, ga_results::genome, parameter_ga::genome_size, GA::get_average_fitness(), GA::get_best_genome(), GA::get_bsf(), independent_runs(), parameter_im::is_im_enabled, parameter_mut::is_real, parameter_sel::k, parameter_mut::low_bound, parameter_sel::lower_bound, make_dir(), parameter_im::migration_interval, parameter_ga::mut_pms, parameter_mut::mutation_method, parameter_mut::mutation_rate, parameter_im::num_immigrants, parameter_im::num_islands, parameter_ga::num_offsprings, parameter_sel::num_parents, parameter_ga::num_replacement, parameter_mut::order, parameter_im::pick_method, parameter_ga::population_size, parameter_pr::print_average_fitness, parameter_pr::print_best_genome, parameter_pr::print_bsf, parameter_pr::print_fitness, print_parameters(), parameter_sel::replace, parameter_im::replace_method, run_islands(), parameter_ga::runs, parameter_ga::sel_pms, parameter_sel::selection_method, parameter_mut::up_bound, parameter_mut::variance, and parameter_pr::where2write.