Project GAIM: island_ga.cpp File Reference
island_ga.cpp File Reference
Functions
ga_results_s run_islands (REAL_(*func)(REAL_ *, size_t), im_parameter_s im_pms, ga_parameter_s ga_pms, pr_parameter_s pr_pms, std::string return_type)
It runs an island model using pthreads.
Variables
pthread_barrier_t barrier
Detailed Description
Defines the Island Model class, which runs a genetic algorithm process across multiple communicating subpopulations.
Definition in file island_ga.cpp.
Function Documentation
run_islands()
ga_results_s run_islands (REAL_(*)(REAL_ *, size_t) func, im_parameter_s im_pms, ga_parameter_s ga_pms, pr_parameter_s pr_pms, std::string return_type)
It runs an island model using pthreads.
Runs an X number of islands in parallel using threads.
Parameters
[in] func A pointer to the fitness function
[in] im_pms Structure of IM parameters
[in] ga_pms Structure of GA parameters
[in] pr_pms Structure of printing parameters
[in] return_type A string that determines which run the genome will be returned. The available options are: (*) "minimum" - the genome with the minimum Euclidean distance is returned (*) "maximum" - the genome with the maximum Euclidean distance is returned (*) "random" - a randomly chosen genome is returned
Returns
A data structure of type ga_results_s with the selected genome.
Create the data directory if it doesn't exist
Set the fitness function for every island
Evolve a GA on each island
Choose from all the islands which genome to return
Definition at line 381 of file island_ga.cpp.
References IM::evolve_islands(), IM::island, make_dir(), parameter_im::num_islands, return_best_results(), and parameter_pr::where2write.
Referenced by ga_optimization(), and ga_optimization_python().
Variable Documentation
barrier
pthread_barrier_t barrier
Definition at line 33 of file island_ga.cpp.
Referenced by _pthread_barrier_destroy(), _pthread_barrier_init(), _pthread_barrier_wait(), IM::evolve_island(), and IM::evolve_islands().