Project GAIM: logging.cpp File Reference
logging.cpp File Reference
Functions
std::string prd (const REAL_ x, const int decDigits, const int width)
Converts a number to a string with specific format and tabs.
std::string center (const std::string s, const int w)
Centers a string so it can be printed in a pretty way.
void print_fitness (std::vector< individual_s > &individual, std::size_t unique_id, std::string write_to)
Prints the fitness of each individual within a population, as well as its ID, either to standard output (stdout) or to a file.
void print_bsf (std::vector< REAL_ > bsf, std::size_t unique_id, std::string write_to)
Prints the best-so-far fitness (BSF) of a population either to standard output (stdout) or to a file.
void print_avg_fitness (std::vector< REAL_ > fit_avg, std::size_t unique_id, std::string write_to)
Prints the average fitness of a population either to standard output (stdout) or to a file.
void print_best_genome (std::vector< REAL_ > best_genome, std::size_t unique_id, std::string write_to)
Prints the genome of an individual of a population with the best fitness either to standard output (stdout) or to a file.
Detailed Description
Manages serialization of fitness (avg or BSF) and genomes, as well as providing prettyprinting.
Definition in file logging.cpp.
Function Documentation
center()
std::string center (const std::string s, const int w)
Centers a string so it can be printed in a pretty way.
Printing Functions.
Parameters
[in] s The input string to be centered
[in] w The width of the total string
Returns
A string that is centered and padded with spaces
Definition at line 55 of file logging.cpp.
Referenced by print_avg_fitness(), print_bsf(), and print_fitness().
prd()
std::string prd (const REAL_ x, const int decDigits, const int width)
Converts a number to a string with specific format and tabs.
Parameters
[in] x Number to be converted to string
[in] decDigits Number of decimal digits to be used
[in] width Width of the string
Returns
A string that contains the number x
Definition at line 37 of file logging.cpp.
Referenced by print_avg_fitness(), print_bsf(), and print_fitness().
print_avg_fitness()
void print_avg_fitness (std::vector< REAL_ > fit_avg, std::size_t unique_id, std::string write_to)
Prints the average fitness of a population either to standard output (stdout) or to a file.
Parameters
[in] fit_avg Average fitness of a population over generations
[in] unique_id This is the thread id in case the Island Model is used otherwise it can be any number of type size_t
[in] write_to A string that defines where the fitness will be displayed ("stdout" or "/path/to/file")
Returns
Nothing. (void)
Definition at line 165 of file logging.cpp.
References center(), is_path_exist(), and prd().
Referenced by GA::evolve(), IM::evolve_island(), and read_parameters_file().
print_best_genome()
void print_best_genome (std::vector< REAL_ > best_genome, std::size_t unique_id, std::string write_to)
Prints the genome of an individual of a population with the best fitness either to standard output (stdout) or to a file.
Parameters
[in] best_genome Vector of the best genome within a population
[in] unique_id This is the thread id in case the Island Model is used otherwise it can be any number of type size_t
[in] write_to A string that defines where the fitness will be displayed ("stdout" or "/path/to/file")
Returns
Nothing. (void)
Definition at line 207 of file logging.cpp.
References is_path_exist().
Referenced by GA::evolve(), IM::evolve_island(), and read_parameters_file().
print_bsf()
void print_bsf (std::vector< REAL_ > bsf, std::size_t unique_id, std::string write_to)
Prints the best-so-far fitness (BSF) of a population either to standard output (stdout) or to a file.
Parameters
[in] bsf Best-so-far individual's fitness over generations
[in] unique_id This is the thread id in case the Island Model is used otherwise it can be any number of type size_t
[in] write_to A string that defines where the fitness will be displayed ("stdout" or "/path/to/file")
Returns
Nothing. (void)
Definition at line 123 of file logging.cpp.
References center(), is_path_exist(), and prd().
Referenced by GA::evolve(), IM::evolve_island(), and read_parameters_file().
print_fitness()
void print_fitness (std::vector< individual_s > & individual, std::size_t unique_id, std::string write_to)
Prints the fitness of each individual within a population, as well as its ID, either to standard output (stdout) or to a file.
Parameters
[in] individual The population vector
[in] unique_id This is the thread id in case the Island Model is used; otherwise it can be any number of type size_t
[in] write_to A string that defines where the fitness will be displayed ("stdout" or "/path/to/file")
Returns
Nothing. (void)
Definition at line 79 of file logging.cpp.
References center(), is_path_exist(), and prd().
Referenced by GA::evolve(), IM::evolve_island(), and read_parameters_file().