Project GAIM: mutation.cpp File Reference
mutation.cpp File Reference
Functions
std::vector< REAL_ > delta_mutation (std::vector< REAL_ > genome, REAL_ mutation_rate=0.5, REAL_ variance=0.5)
This function implements a delta mutation operator meaning that for every gene in the genome a random number drawn from a normal distribution and it is added to the gene value according to a probability.
std::vector< REAL_ > random_mutation (std::vector< REAL_ > genome, REAL_ a, REAL_ b, bool is_real)
Random mutation operator.
REAL_ delta (REAL_ x, size_t time, size_t tot_time, size_t r=1)
Auxiliary function for decaying mutation, used in time-dependent non-uniform mutation.
std::vector< REAL_ > nonuniform_mutation (std::vector< REAL_ > genome, size_t time, size_t generations, size_t order, REAL_ a, REAL_ b)
Non-uniform mutation operator.
std::vector< REAL_ > fusion_mutation (std::vector< REAL_ > genome, REAL_ a, REAL_ b, bool is_real)
Fusion mutation operator method.
std::vector< REAL_ > swap_mutation (std::vector< REAL_ > genome)
Swap mutation operator method.
Detailed Description
Provides extra mutation operators (which produce a mutant genome from a
current genome) usable by default within GAIM. Some operators should be called multiple times per generation.
Definition in file mutation.cpp.
Function Documentation
delta()
REAL_ delta (REAL_ x, size_t time, size_t tot_time, size_t r = 1)
Auxiliary function for decaying mutation, used in time-dependent non-uniform mutation.
Performs the following operation
[1]
Parameters
[in] x Gene's numerical value
[in] time Current time step (generation)
[in] tot_time Total number of time steps (generations)
[in] r Magnitude of order that the LHS of [1] affects the mutation
Returns
A mutated gene value.
Definition at line 114 of file mutation.cpp.
Referenced by pcg_detail::engine< xtype, itype, output_mixin, output_previous, stream_mixin, multiplier_mixin >::advance(), pcg_detail::extended< table_pow2, advance_pow2, baseclass, extvalclass, kdd >::advance_table(), pcg_detail::engine< xtype, itype, output_mixin, output_previous, stream_mixin, multiplier_mixin >::backstep(), delta_mutation(), pcg_detail::engine< xtype, itype, output_mixin, output_previous, stream_mixin, multiplier_mixin >::discard(), pcg_detail::inside_out< baseclass >::external_advance(), and nonuniform_mutation().
delta_mutation()
std::vector<REAL_> delta_mutation (std::vector< REAL_ > genome, REAL_ mutation_rate = 0.5, REAL_ variance = 0.5)
This function implements a delta mutation operator meaning that for every gene in the genome a random number drawn from a normal distribution and it is added to the gene value according to a probability.
Extra Mutation functions.
Specifically, the mutation delta is drawn from the Normal/Gaussian distribution with mean 0 and standard deviation defined by the argument variance.
Parameters
[in] genome The genome (genes) of an individual
[in] mutation_rate Mutation rate (probability threshold)
[in] variance Standard deviation of the normal distribution from which the increment/decrement is drawn
Returns
A vector of floats (mutated genome)
Definition at line 43 of file mutation.cpp.
References delta().
Referenced by GA::mutation(), and PYBIND11_MODULE().
fusion_mutation()
std::vector<REAL_> fusion_mutation (std::vector< REAL_ > genome, REAL_ a, REAL_ b, bool is_real)
Fusion mutation operator method.
Performs a fusion mutation operation. It checks if the genome has unique elements. If doesn't have, it removes the repetitions and replaces them by new random (uniformly drawn) values.
Parameters
[in] genome Individual's genome
[in] a Lower bound of sampling interval
[in] b Upper bound of sampling interval
[in] is_real Determines if the interval is in the set of reals or integers (to use when REAL_ is set to INT)
Returns
A mutated genome.
Definition at line 184 of file mutation.cpp.
Referenced by PYBIND11_MODULE().
nonuniform_mutation()
std::vector<REAL_> nonuniform_mutation (std::vector< REAL_ > genome, size_t time, size_t generations, size_t order, REAL_ a, REAL_ b)
Non-uniform mutation operator.
Performs a non-uniform mutation which is time-dependent, decaying over time. The mutation is computed as or based on a random choice between -1 or 1, respectively.
Parameters
[in] genome Individual's genome
[in] time Current generation (time step)
[in] generations Total number of generations (total time steps)
[in] order Power of mutation rate
[in] a Lower boundary of interval [a, b]
[in] b Upper boundary of interval [a, b]
Returns
A mutated genome.
Definition at line 142 of file mutation.cpp.
References delta().
Referenced by PYBIND11_MODULE().
random_mutation()
std::vector<REAL_> random_mutation (std::vector< REAL_ > genome, REAL_ a, REAL_ b, bool is_real)
Random mutation operator.
Performs a random mutation on the genome of an individual. A random mutation takes place at a random gene and replaces the current value of the gene with a new random one drawn from a uniform distribution in the interval [a, b].
Parameters
[in] genome Individual's genome (genes)
[in] a Lower boundary of interval [a, b]
[in] b Upper boundary of interval [a, b]
[in] is_real Determines if the interval is in the set of reals or integers (to use when REAL_ is set to INT)
Returns
A mutated genome (vector of type REAL_).
Definition at line 78 of file mutation.cpp.
Referenced by PYBIND11_MODULE().
swap_mutation()
std::vector<REAL_> swap_mutation (std::vector< REAL_ > genome)
Swap mutation operator method.
Performs a swap mutation operation. It randomly picks up two genes on the same genome and swaps them.
Note
The swap mutation operator is useful in cases of permutations (for instance in solving problems such as the Traveling Salesman Problem).
Parameters
[in] genome Individual's genome
Returns
A mutated genome.
Definition at line 230 of file mutation.cpp.
Referenced by PYBIND11_MODULE().