Project GAIM: pcg_extras Namespace Reference
pcg_extras Namespace Reference
Classes
struct printable_typename
class seed_seq_from
struct static_arbitrary_seed
Typedefs
typedef __uint128_t pcg128_t
typedef uint8_t bitcount_t
Functions
template<typename CharT , typename Traits >
std::basic_ostream< CharT, Traits > & operator<< (std::basic_ostream< CharT, Traits > &out, pcg128_t value)
template<typename CharT , typename Traits >
std::basic_istream< CharT, Traits > & operator>> (std::basic_istream< CharT, Traits > &in, pcg128_t &value)
template<typename CharT , typename Traits >
std::basic_ostream< CharT, Traits > & operator<< (std::basic_ostream< CharT, Traits > &out, uint8_t value)
template<typename CharT , typename Traits >
std::basic_istream< CharT, Traits > & operator>> (std::basic_istream< CharT, Traits > &in, uint8_t target)
std::ostream & operator<< (std::ostream &out, uint8_t value)
std::istream & operator>> (std::istream &in, uint8_t &value)
template<typename itype >
itype unxorshift (itype x, bitcount_t bits, bitcount_t shift)
template<typename itype >
itype rotl (itype value, bitcount_t rot)
template<typename itype >
itype rotr (itype value, bitcount_t rot)
uint8_t rotr (uint8_t value, bitcount_t rot)
uint16_t rotr (uint16_t value, bitcount_t rot)
uint32_t rotr (uint32_t value, bitcount_t rot)
uint64_t rotr (uint64_t value, bitcount_t rot)
template<class SrcIter , class DestIter >
SrcIter uneven_copy_impl (SrcIter src_first, DestIter dest_first, DestIter dest_last, std::true_type)
template<class SrcIter , class DestIter >
SrcIter uneven_copy_impl (SrcIter src_first, DestIter dest_first, DestIter dest_last, std::false_type)
template<class SrcIter , class DestIter >
SrcIter uneven_copy (SrcIter src_first, DestIter dest_first, DestIter dest_last)
template<size_t size, typename SeedSeq , typename DestIter >
void generate_to_impl (SeedSeq &&generator, DestIter dest, std::true_type)
template<size_t size, typename SeedSeq , typename DestIter >
void generate_to_impl (SeedSeq &&generator, DestIter dest, std::false_type)
template<size_t size, typename SeedSeq , typename DestIter >
void generate_to (SeedSeq &&generator, DestIter dest)
template<typename UInt , size_t i = 0UL, size_t N = i+1UL, typename SeedSeq >
UInt generate_one (SeedSeq &&generator)
template<typename RngType >
auto bounded_rand (RngType &rng, typename RngType::result_type upper_bound) -> typename RngType::result_type
template<typename Iter , typename RandType >
void shuffle (Iter from, Iter to, RandType &&rng)
template<typename T >
std::ostream & operator<< (std::ostream &out, printable_typename< T >)
Typedef Documentation
bitcount_t
typedef PCG_BITCOUNT_T pcg_extras::bitcount_t
Definition at line 108 of file pcg_extras.hpp.
pcg128_t
typedef pcg_extras::uint_x4< uint32_t, uint64_t > pcg_extras::pcg128_t
Definition at line 82 of file pcg_extras.hpp.
Function Documentation
bounded_rand()
template<typename RngType > auto pcg_extras::bounded_rand (RngType & rng, typename RngType::result_type upper_bound) -> typename RngType::result_type
Definition at line 517 of file pcg_extras.hpp.
Referenced by pcg_detail::engine< xtype, itype, output_mixin, output_previous, stream_mixin, multiplier_mixin >::operator()(), pcg_detail::extended< table_pow2, advance_pow2, baseclass, extvalclass, kdd >::operator()(), and shuffle().
generate_one()
template<typename UInt , size_t i = 0UL, size_t N = i+1UL, typename SeedSeq > UInt pcg_extras::generate_one (SeedSeq && generator) inline
Definition at line 509 of file pcg_extras.hpp.
generate_to()
template<size_t size, typename SeedSeq , typename DestIter > void pcg_extras::generate_to (SeedSeq && generator, DestIter dest) inline
Definition at line 494 of file pcg_extras.hpp.
generate_to_impl() [1/2]
template<size_t size, typename SeedSeq , typename DestIter > void pcg_extras::generate_to_impl (SeedSeq && generator, DestIter dest, std::false_type)
Definition at line 465 of file pcg_extras.hpp.
References uneven_copy().
generate_to_impl() [2/2]
template<size_t size, typename SeedSeq , typename DestIter > void pcg_extras::generate_to_impl (SeedSeq && generator, DestIter dest, std::true_type) inline
Definition at line 458 of file pcg_extras.hpp.
operator<<() [1/4]
template<typename CharT , typename Traits > std::basic_ostream<CharT,Traits>& pcg_extras::operator<< (std::basic_ostream< CharT, Traits > & out, pcg128_t value)
Definition at line 124 of file pcg_extras.hpp.
operator<<() [2/4]
template<typename CharT , typename Traits > std::basic_ostream<CharT,Traits>& pcg_extras::operator<< (std::basic_ostream< CharT, Traits > & out, uint8_t value)
Definition at line 216 of file pcg_extras.hpp.
operator<<() [3/4]
template<typename T > std::ostream& pcg_extras::operator<< (std::ostream & out, printable_typename< T >)
Definition at line 619 of file pcg_extras.hpp.
operator<<() [4/4]
std::ostream& pcg_extras::operator<< (std::ostream & out, uint8_t value) inline
Definition at line 242 of file pcg_extras.hpp.
operator>>() [1/3]
template<typename CharT , typename Traits > std::basic_istream<CharT,Traits>& pcg_extras::operator>> (std::basic_istream< CharT, Traits > & in, pcg128_t & value)
Definition at line 168 of file pcg_extras.hpp.
operator>>() [2/3]
template<typename CharT , typename Traits > std::basic_istream<CharT,Traits>& pcg_extras::operator>> (std::basic_istream< CharT, Traits > & in, uint8_t target)
Definition at line 223 of file pcg_extras.hpp.
operator>>() [3/3]
std::istream& pcg_extras::operator>> (std::istream & in, uint8_t & value) inline
Definition at line 247 of file pcg_extras.hpp.
rotl()
template<typename itype > itype pcg_extras::rotl (itype value, bitcount_t rot) inline
Definition at line 294 of file pcg_extras.hpp.
rotr() [1/5]
template<typename itype > itype pcg_extras::rotr (itype value, bitcount_t rot) inline
Definition at line 306 of file pcg_extras.hpp.
Referenced by pcg_detail::xsh_rr_mixin< xtype, itype >::output(), pcg_detail::xsl_rr_mixin< xtype, itype >::output(), and pcg_detail::xsl_rr_rr_mixin< xtype, itype >::output().
rotr() [2/5]
uint16_t pcg_extras::rotr (uint16_t value, bitcount_t rot) inline
Definition at line 332 of file pcg_extras.hpp.
rotr() [3/5]
uint32_t pcg_extras::rotr (uint32_t value, bitcount_t rot) inline
Definition at line 338 of file pcg_extras.hpp.
rotr() [4/5]
uint64_t pcg_extras::rotr (uint64_t value, bitcount_t rot) inline
Definition at line 345 of file pcg_extras.hpp.
rotr() [5/5]
uint8_t pcg_extras::rotr (uint8_t value, bitcount_t rot) inline
Definition at line 326 of file pcg_extras.hpp.
shuffle()
template<typename Iter , typename RandType > void pcg_extras::shuffle (Iter from, Iter to, RandType && rng)
Definition at line 531 of file pcg_extras.hpp.
References bounded_rand().
Referenced by IM::move_immigrants(), and IM::select_ind2migrate().
uneven_copy()
template<class SrcIter , class DestIter > SrcIter pcg_extras::uneven_copy (SrcIter src_first, DestIter dest_first, DestIter dest_last) inline
Definition at line 441 of file pcg_extras.hpp.
References uneven_copy_impl().
Referenced by generate_to_impl().
uneven_copy_impl() [1/2]
template<class SrcIter , class DestIter > SrcIter pcg_extras::uneven_copy_impl (SrcIter src_first, DestIter dest_first, DestIter dest_last, std::false_type)
Definition at line 412 of file pcg_extras.hpp.
uneven_copy_impl() [2/2]
template<class SrcIter , class DestIter > SrcIter pcg_extras::uneven_copy_impl (SrcIter src_first, DestIter dest_first, DestIter dest_last, std::true_type)
Definition at line 383 of file pcg_extras.hpp.
Referenced by uneven_copy().
unxorshift()
template<typename itype > itype pcg_extras::unxorshift (itype x, bitcount_t bits, bitcount_t shift) inline
Definition at line 265 of file pcg_extras.hpp.
Referenced by pcg_detail::rxs_m_xs_mixin::unoutput().