Project GAIM: parallel_ga.cpp File Reference
parallel_ga.cpp File Reference
Functions
ga_results independent_runs (REAL_(*func)(REAL_ *, size_t), ga_parameter_s *ga_pms, pr_parameter_s *pr_pms, std::string return_type)
It runs X independent GAs in parallel using threads.
Detailed Description
Implements parallel independent runs of a GA within an experiment so that you can average over separate evolutionary trajectories.
Definition in file parallel_ga.cpp.
Function Documentation
independent_runs()
ga_results independent_runs (REAL_(*)(REAL_ *, size_t) func, ga_parameter_s * ga_pms, pr_parameter_s * pr_pms, std::string return_type)
It runs X independent GAs in parallel using threads.
Multithread and Islands functions declarations.
Runs an X number of GAs in parallel and independently using threads.
Parameters
[in] func A pointer to the fitness function
[in] ga_pms Structure of GA parameters
[in] pr_pms Structure of printing parameters
[in] return_type A string that determines which run the genome will be returned. The available options are: (*) "minimum" - the genome with the minimum Euclidean distance is returned (*) "maximum" - the genome with the maximum Euclidean distance is returned (*) "random" - a randomly chosen genome is returned
Returns
A data structure of type ga_results_s with the selected genome.
Create the data directory if it doesn't exist
Set the fitness function for every run
Instantiate threads and GAs
Join threads
Choose from all the runs which genome to return
Definition at line 45 of file parallel_ga.cpp.
References GA::evolve(), parameter_ga::generations, make_dir(), return_best_results(), parameter_ga::runs, and parameter_pr::where2write.
Referenced by ga_optimization(), and ga_optimization_python().