Project GAIM: parameters.cpp File Reference
parameters.cpp File Reference
Functions
std::tuple< ga_parameter_s, pr_parameter_s, im_parameter_s > read_parameters_file (const char *fname)
Reads GAIM config files containing Genetic Algorithm, Island Model and printing parameters.
void print_parameters (ga_parameter_s ga_pms, pr_parameter_s pr_pms, im_parameter_s im_pms)
Prints parameters to a .dat file, or to stdout if "stdout" is specified.
Detailed Description
Provides I/O of GAIM configuration files holding GA, IM, and printing/debug parameters.
Definition in file parameters.cpp.
Function Documentation
print_parameters()
void print_parameters (ga_parameter_s ga_pms, pr_parameter_s pr_pms, im_parameter_s im_pms)
Prints parameters to a .dat file, or to stdout if "stdout" is specified.
Prints all the parameters to the standard output (if "stdout" is specified as where2write in the printing params) and to a file for debugging purposes.
Parameters
[in] ga_pms Structure of GA parameters
[in] pr_pms Structure of printing parameters
[in] im_pms Structure of IM parameters
Returns
Nothing (void function)
Definition at line 217 of file parameters.cpp.
References parameter_ga::clipping, parameter_ga::clipping_fname, parameter_pr::experiment_name, parameter_ga::generations, parameter_ga::genome_size, parameter_im::is_im_enabled, parameter_im::migration_interval, parameter_im::num_immigrants, parameter_im::num_islands, parameter_ga::num_offsprings, parameter_ga::num_replacement, parameter_im::pick_method, parameter_ga::population_size, parameter_pr::print_average_fitness, parameter_pr::print_best_genome, parameter_pr::print_bsf, parameter_pr::print_fitness, parameter_im::replace_method, parameter_ga::runs, and parameter_pr::where2write.
Referenced by ga_optimization().
read_parameters_file()
std::tuple<ga_parameter_s, pr_parameter_s, im_parameter_s> read_parameters_file (const char * fname)
Reads GAIM config files containing Genetic Algorithm, Island Model and printing parameters.
Parameters files.
Reads a configuration file (.cfg) of libconfig format, parses it and loads the parameters into the internal data structures.
Parameters
[in] fname Configuration filename (libconfig format).
Returns
A tuple of three structures (parameter_s, print_params_s, im_parameter_s) -> (GA, printing, IM).
Definition at line 40 of file parameters.cpp.
References parameter_ga::a, parameter_im::adj_list_fname, parameter_ga::b, parameter_ga::clipping, parameter_ga::clipping_fname, parameter_pr::experiment_name, parameter_ga::generations, parameter_ga::genome_size, parameter_im::is_im_enabled, is_path_exist(), parameter_im::migration_interval, mkdir_(), parameter_im::num_immigrants, parameter_im::num_islands, parameter_ga::num_offsprings, parameter_ga::num_replacement, parameter_im::pick_method, parameter_ga::population_size, parameter_pr::print_average_fitness, print_avg_fitness(), parameter_pr::print_best_genome, print_best_genome(), print_bsf(), parameter_pr::print_bsf, print_fitness(), parameter_pr::print_fitness, parameter_im::replace_method, parameter_ga::runs, and parameter_pr::where2write.