Project GAIM: pygaim.cpp File Reference
pygaim.cpp File Reference
Functions
PYBIND11_MODULE (pygaim, m)
Function Documentation
PYBIND11_MODULE()
PYBIND11_MODULE (pygaim , m)
Definition at line 36 of file pygaim.cpp.
References parameter_ga::a, parameter_im::adj_list_fname, parameter_ga::b, GA::clip_genome(), parameter_ga::clipping_fname, GA::crossover(), delta_mutation(), discrete_crossover(), GA::evaluation(), GA::evolve(), IM::evolve_island(), parameter_pr::experiment_name, individual::fitness, flat_crossover(), fusion_mutation(), ga_optimization(), parameter_ga::generations, individual::genome, parameter_ga::genome_size, GA::get_average_fitness_rec(), GA::get_bsf(), individual::id, parameter_im::is_im_enabled, individual::is_selected, ktournament_selection(), linear_rank_selection(), individual::lower_limit, parameter_im::migration_interval, IM::move_immigrants(), GA::mutation(), GA::next_generation(), nonuniform_mutation(), parameter_im::num_immigrants, parameter_im::num_islands, parameter_ga::num_offsprings, parameter_ga::num_replacement, one_point_crossover(), order_one_crossover(), parameter_im::pick_method, parameter_ga::population_size, parameter_pr::print_average_fitness, parameter_pr::print_best_genome, parameter_pr::print_bsf, parameter_pr::print_fitness, GA::pycallback(), random_mutation(), random_selection(), IM::read_connectivity_graph(), parameter_im::replace_method, GA::reset_selection_flags(), roulette_wheel_selection(), IM::run_islands(), GA::run_one_generation(), parameter_ga::runs, IM::select_ind2migrate(), GA::selection(), GA::sort_population(), stochastic_roulette_wheel_selection(), swap_mutation(), truncation_selection(), two_point_crossover(), uniform_crossover(), individual::upper_limit, parameter_pr::where2write, and whitley_selection().