Project GAIM: selection.cpp File Reference
selection.cpp File Reference
Functions
std::vector< individual_s > ktournament_selection (std::vector< individual_s > &population, size_t num_parents, int k, bool replace)
Implements a k-tournament selection.
std::vector< individual_s > truncation_selection (std::vector< individual_s > &population, size_t num_parents, size_t low_bound, bool replace)
Implements a truncation selection operator.
std::vector< individual_s > linear_rank_selection (std::vector< individual_s > &population, size_t num_parents, bool replace)
Implements a linear rank selection mechanism.
std::vector< individual_s > random_selection (std::vector< individual_s > &population, size_t num_parents, bool replace)
Implements a random selection.
std::vector< individual_s > roulette_wheel_selection (std::vector< individual_s > &population, size_t num_parents, bool replace)
Implements a roulette-wheel selection (or fitness-proportionate selection) mechanism.
std::vector< individual_s > stochastic_roulette_wheel_selection (std::vector< individual_s > &population, size_t num_parents, bool replace)
Parent selection method proposed by Lipowski A.
REAL_ calculate_whitley_factor (REAL_ bias)
Calculates the Whitley factor used in Whitley's selection method.
std::vector< individual_s > whitley_selection (std::vector< individual_s > &population, REAL_ bias, size_t num_parents, bool replace)
Parent selection method proposed by Darrell Whitley in his GENITOR paper: "The GENITOR Algorithm and Selection Pressure: Why Rank-Based Allocation of Reproductive Trials is Best", ", D.
Detailed Description
Provides extra selection operators (which identify reproducing pairs to create the next generation) usable by default within GAIM.
Definition in file selection.cpp.
Function Documentation
calculate_whitley_factor()
REAL_ calculate_whitley_factor (REAL_ bias)
Calculates the Whitley factor used in Whitley's selection method.
Parameters
[in] bias Governs how strong one would like to favor high ranked individuals.
Returns
The factor bias - sqrt(bias^2 - 4 * (bias - 1) * rand(0, 1))/2/(bias-1)
Warning
Bias should be in (1, 2]
See also
whitley_selection()
Definition at line 451 of file selection.cpp.
References float_random().
Referenced by whitley_selection().
ktournament_selection()
std::vector<individual_s> ktournament_selection (std::vector< individual_s > & population, size_t num_parents, int k, bool replace)
Implements a k-tournament selection.
Extra Selection functions.
Parameters
[in] population A vector of the entire population of individuals.
[in] num_parents Number of individuals being selected for reproduction.
[in] k An integer that defines the tournament size (how many individuals from the population will be drawn randomly).
[in] replace Determines if the individuals will be selected with replacement or not.
Returns
A vector of individual_s structures (selected parents).
Definition at line 41 of file selection.cpp.
References individual::fitness, individual::genome, individual::is_selected, and remove_at().
Referenced by PYBIND11_MODULE(), and GA::selection().
linear_rank_selection()
std::vector<individual_s> linear_rank_selection (std::vector< individual_s > & population, size_t num_parents, bool replace)
Implements a linear rank selection mechanism.
The population is sorted based on the fitness of each individual and then a selection probability is assigned to each individual based on their rank.
Parameters
[in] population A vector of the entire population of individuals
[in] num_parents Number of individuals being selected for reproduction
[in] replace Determines if the individuals will be selected with replacement or not.
Returns
A vector of individual_s structures (or the selected parents).
Definition at line 176 of file selection.cpp.
References compare_fitness().
Referenced by PYBIND11_MODULE().
random_selection()
std::vector<individual_s> random_selection (std::vector< individual_s > & population, size_t num_parents, bool replace)
Implements a random selection.
It randomly picks up one individual from the entire population.
Parameters
[in] population A vector of the entire population of individuals.
[in] num_parents Number of individuals being selected for reproduction.
[in] replace Determines if the individuals will be selected with replacement or not.
Returns
A vector of indivudual_s as parents.
Definition at line 251 of file selection.cpp.
References int_random().
Referenced by PYBIND11_MODULE().
roulette_wheel_selection()
std::vector<individual_s> roulette_wheel_selection (std::vector< individual_s > & population, size_t num_parents, bool replace)
Implements a roulette-wheel selection (or fitness-proportionate selection) mechanism.
The fitness function observes a fitness for each individual and the share of the population's total fitness is used to associate a selection
probability with each individual.
Parameters
[in] population A vector of the entire population of individuals.
[in] num_parents Number of individuals being selected for reproduction.
[in] replace Determines if the individuals will be selected with replacement or not.
Returns
A vector of individual_s which corresponds to the selected parents.
Definition at line 306 of file selection.cpp.
References average_fitness(), cumulative_fitness(), and float_random().
Referenced by PYBIND11_MODULE().
stochastic_roulette_wheel_selection()
std::vector<individual_s> stochastic_roulette_wheel_selection (std::vector< individual_s > & population, size_t num_parents, bool replace)
Parent selection method proposed by Lipowski A.
and Lipowska D. in "Roulette wheel selection via stochastic acceptance", 2011. The method is a variant of the roulette wheel where the maximum fitness is used to normalize individuals' fitness and transform them to a probability. The latter is used to decide probabilisticly if the chosen individual will be allowed to get offsprings.
Parameters
[in] population A vector of the entire population of individuals.
[in] num_parents Number of individuals being selected for reproduction.
[in] replace Determines if the individuals will be selected with replacement or not.
Returns
A vector of indivudual_s (selected parents).
Definition at line 385 of file selection.cpp.
References float_random(), int_random(), maximum_fitness(), nonselected_maximum_fitness(), and remove_at().
Referenced by PYBIND11_MODULE().
truncation_selection()
std::vector<individual_s> truncation_selection (std::vector< individual_s > & population, size_t num_parents, size_t low_bound, bool replace)
Implements a truncation selection operator.
The population is sorted based on the fitness of each individual and a percentage of individuals that will be discarded is computed based on the given number of offsprings (lambda).
Parameters
[in] population A vector of the entire population of individuals
[in] num_parents Number of individuals being selected for reproduction
[in] low_bound The lowest index from which the selection begins.
[in] replace Determines if the individuals will be selected with replacement or not.
Returns
A vector of individual_s structures (or the selected parents).
Definition at line 114 of file selection.cpp.
References compare_fitness(), and int_random().
Referenced by PYBIND11_MODULE().
whitley_selection()
std::vector<individual_s> whitley_selection (std::vector< individual_s > & population, REAL_ bias, size_t num_parents, bool replace)
Parent selection method proposed by Darrell Whitley in his GENITOR paper: "The GENITOR Algorithm and Selection Pressure: Why Rank-Based Allocation of Reproductive Trials is Best", ", D.
Whitley, 2000.
Parameters
[in] population A vector of the entire population of individuals.
[in] bias The bias that controls how strongly the high rank individuals are favored.
[in] num_parents Number of individuals being selected for reproduction.
[in] replace Determines if the individuals will be selected with replacement or not.
Returns
A vector of indivudual_s (selected parents).
See also
calculate_whitley_factor() On how to calculate the Whitley factor.
Definition at line 478 of file selection.cpp.
References calculate_whitley_factor().
Referenced by PYBIND11_MODULE().