Project GAIM: test_functions.cpp File Reference
test_functions.cpp File Reference
Functions
REAL_ sphere (std::vector< REAL_ > &x)
Sphere cost function.
REAL_ rastrigin (std::vector< REAL_ > &x)
Rastrigin cost function.
REAL_ schwefel (std::vector< REAL_ > &x)
Schwefel cost function.
REAL_ griewank (std::vector< REAL_ > &x)
Griewangk cost function.
int distance (int x, int y)
REAL_ tsm (std::vector< REAL_ > &x)
Detailed Description
Furnishes a small collection of standard test objective functions typically used as benchmarks in numerical optimization.
Definition in file test_functions.cpp.
Function Documentation
distance()
int distance (int x, int y)
Definition at line 110 of file test_functions.cpp.
Referenced by pcg_detail::extended< table_pow2, advance_pow2, baseclass, extvalclass, kdd >::advance(), pcg_detail::extended< table_pow2, advance_pow2, baseclass, extvalclass, kdd >::backstep(), pcg_detail::engine< xtype, itype, output_mixin, output_previous, stream_mixin, multiplier_mixin >::distance(), pcg_detail::inside_out< baseclass >::external_advance(), and tsm().
griewank()
REAL_ griewank (std::vector< REAL_ > & x)
Griewangk cost function.
Griewangk cost function
Parameters
[in] x Vector
Returns
A number indicating the cost
Definition at line 97 of file test_functions.cpp.
rastrigin()
REAL_ rastrigin (std::vector< REAL_ > & x)
Rastrigin cost function.
Rastrigin cost function
Parameters
[in] x Vector
Returns
A number indicating the cost
Definition at line 58 of file test_functions.cpp.
schwefel()
REAL_ schwefel (std::vector< REAL_ > & x)
Schwefel cost function.
Schwefel cost function
Parameters
[in] x Vector
Returns
A number indicating the cost
Definition at line 77 of file test_functions.cpp.
sphere()
REAL_ sphere (std::vector< REAL_ > & x)
Sphere cost function.
Demo objective/fitness functions End-user can define more at her/his will.
Sphere cost function
Parameters
[in] x Vector
Returns
A number indicating the cost
Definition at line 39 of file test_functions.cpp.
Referenced by GA::GA().
tsm()
REAL_ tsm (std::vector< REAL_ > & x)
Definition at line 142 of file test_functions.cpp.
References distance().